Summary       : GNU Find Utilities (find, xargs)
Summary(de)   : GNU-Suchprogramme (find, xargs)
Summary(fr)   : Utilitaires de recherche de GNU (find, xargs)
Summary(pl)   : GNU narzêdzia do odnajdywania plików (find, xargs)
Summary(tr)   : GNU dosya arama araçlarý
Name          : findutils
Version       : 4.1.7
Release       : 1
License       : GPL
Group         : Applications/File
Group(de)     : Applikationen/Datei
Group(pl)     : Aplikacje/Pliki

Packager      : Frank Naumann <fnaumann@freemint.de>
Vendor        : Sparemint
URL           : http://www.gnu.org/software/findutils/

Prereq        : /sbin/install-info
BuildRequires :	texinfo

Prefix        : %{_prefix}
Docdir        : %{_prefix}/doc
BuildRoot     : %{_tmppath}/%{name}-root

Source0: ftp://alpha.gnu.org/gnu/findutils-%{version}.tar.gz
Source1: updatedb.cron
Patch0: findutils-info.patch
Patch1: findutils-pl_manpages.patch
Patch2: findutils-mktemp.patch
Patch3: findutils-getshort.patch
Patch4: findutils-DESTDIR.patch
Patch5: findutils-am-workaround.patch
Patch6: findutils-4.1-mint.patch
Patch7: findutils-4.1-getopt.patch


%description
The findutils package contains programs which will help you locate
files on your system. The find utility searches through a hierarchy of
directories looking for files which match a certain set of criteria
(such as a filename pattern). The locate utility searches a database
(create by updatedb) to quickly find a file matching a given pattern.
The xargs utility builds and executes command lines from standard
input arguments (usually lists of file names generated by the find
command).

%description -l de
Das findutils-Paket enthält Programme, die dabei helfen, Dateien auf
Ihrem System zu finden. Das Find-Utility durchsucht die
Verzeichnishierarchie nach Dateien, die zu bestimmten Kriterien (z.B.
Dateiname) passen. Das locate-Utility durchsucht eine Datenbank
(erzeugt durch updatedb), um die Dateien schneller finden zu können.
xargs konstruiert Kommandozeilen von der Standardeingabe (z.B.
Dateilisten, die von find erzeugt werden), und führt sie aus.

%description -l fr
Ce package contient des programmes pour vous aider à localiser des
fichiers sur votre système. Le programme find peut rechercher à
travers une hiérarchie de répertoires des fichiers conformes à
certains critères (comme un type de nom).

%description -l pl
W pakiecie znajduj± siê narzêdzia pozwalaj±ce na poszukiwanie
okre¶lonych plików. Program find s³u¿y do poszukiwania w drzewie
katalogów plików o okre¶lonych parametrach, jak nazwa, uprawnienia,
typ czy data ostatniej modyfikacji.

%description -l tr
Bu pakette yer alan yazýlýmlar sisteminizde yer alan dosyalarý
bulabilmeniz için hazýrlanmýþlardýr. find programý ile belirli
özellikleri olan bir yazýlýmý bir dizin hiyerarþisi altýnda
arayabilirsiniz.


%prep
%setup  -q
%patch0 -p1 
%patch1 -p1
%patch2 -p1 
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1 -b .mint
%patch7 -p1 -b .getopt


%build
CFLAGS="${RPM_OPT_FLAGS} -D_GNU_SOURCE" \
./configure \
	--prefix=%{_prefix} \
	--exec-prefix=%{_prefix} \
	--libexecdir=%{_prefix}/lib/findutils \
	--localstatedir=/var/lib \
	--disable-dependency-tracking
make 


%install
[ "${RPM_BUILD_ROOT}" != "/" ] && rm -rf ${RPM_BUILD_ROOT}

make install \
	prefix=${RPM_BUILD_ROOT}%{_prefix} \
	exec_prefix=${RPM_BUILD_ROOT}%{_prefix} \
	libexecdir=${RPM_BUILD_ROOT}%{_prefix}/lib/findutils \
	localstatedir=${RPM_BUILD_ROOT}/var/lib \
	mandir=${RPM_BUILD_ROOT}%{_prefix}/share/man

mkdir -p ${RPM_BUILD_ROOT}%{_prefix}/share/man/pl/man1
install -m 644 pl/*.1  ${RPM_BUILD_ROOT}%{_prefix}/share/man/pl/man1/

mkdir -p ${RPM_BUILD_ROOT}/etc/cron.daily
install -m 644 %{SOURCE1} ${RPM_BUILD_ROOT}/etc/cron.daily/updatedb.cron

# compress manpages
gzip -9fn ${RPM_BUILD_ROOT}%{_prefix}/info/find.info*
gzip -9fn ${RPM_BUILD_ROOT}%{_prefix}/share/man/man*/* ||:
gzip -9fn ${RPM_BUILD_ROOT}%{_prefix}/share/man/*/man*/* ||:

strip ${RPM_BUILD_ROOT}%{_prefix}/bin/* ||:
stack --fix=80k ${RPM_BUILD_ROOT}%{_prefix}/bin/* ||:


%clean
[ "${RPM_BUILD_ROOT}" != "/" ] && rm -rf ${RPM_BUILD_ROOT}


%post
mkdir -p /var/lib
/sbin/install-info %{_prefix}/info/find.info.gz %{_prefix}/info/dir

%preun
if [ $1 = 0 ]; then
    /sbin/install-info --delete %{_prefix}/info/find.info.gz %{_prefix}/info/dir
fi


%files
%defattr(-,root,root)
%doc ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README THANKS TODO
%config /etc/cron.daily/updatedb.cron
%{_prefix}/bin/*
%{_prefix}/info/find.info*
%{_prefix}/lib/findutils
%{_prefix}/share/man/man*/*
%{_prefix}/share/man/*/man*/*


%changelog
* Fri Sep 14 2001 Frank Naumann <fnaumann@freemint.de>
- updated to 4.1.7

* Wed Apr 19 2000 Frank Naumann <fnaumann@freemint.de>
- rebuild against new MiNTLib 0.55

* Wed Aug 25 1999 Frank Naumann <fnaumann@freemint.de>
- compressed manpages
- correct Packager and Vendor
