Summary:	Utility to clean up & pretty print html files
Name:		tidy
Version:	030401
Serial:		19
Release:	1
Group:		Utilities/Text
Copyright:	BSD Style
URL:		http://tidy.sourceforge.net/
Source0:	http://tidy.sourceforge.net/src/%{name}_src.tgz
Source1:	http://tidy.sourceforge.net/docs/%{name}_docs.tgz
Patch:          %{name}-%{version}-mint.patch.gz
Prefix:         %{_prefix}
BuildRoot:	%{_tmppath}/%{name}-%{version}-root
Distribution:   Sparemint
Vendor:         Sparemint
Packager:       Edgar Aichinger <eaiching@t0.or.at>
Summary(de):    Utility, um HTML-Seiten zu säubern und zu formatieren

%description
When editing HTML it's easy to make mistakes. Wouldn't it be nice if there was
a simple way to fix these mistakes automatically and tidy up sloppy editing
into nicely layed out markup? Well now there is! Dave Raggett's HTML TIDY is a
free utility for doing just that. It also works great on the atrociously hard
to read markup generated by specialized HTML editors and conversion tools, and
can help you identify where you need to pay further attention on making your
pages more accessible to people with disabilities.

%description -l de
Beim Editieren von HTML ist es leicht, Fehler zu machen. Wäre es nicht nett,
wenn es einen einfachen Weg gäbe, solche Fehler automatisch zu reparieren und
und schlampigen Editierstil in hübsch formatierten Code zu wandeln? Nun, das 
gibt es jetzt! Dave Raggett's HTML TIDY ist ein freies Utility, um genau das 
zu tun. Es arbeitet auch gut mit abscheulich schlecht zu lesendem Code, wie er
von speziellen HTML-Editoren und -Konvertern erzeugt wird, und kann Ihnen 
helfen, festzustellen, wo Sie mehr Hand anlegen müssen, um Ihre Seiten für
viele Besucher erreichbar zu machen.

%prep
%setup -q -n %{name} -b 1
%patch -p1 -b .mint

%build
cd build/gmake; make runinst_prefix=%{prefix} devinst_prefix=%{prefix}

%install
rm -rf ${RPM_BUILD_ROOT}
cd build/gmake; make runinst_prefix=${RPM_BUILD_ROOT}%{prefix} devinst_prefix=${RPM_BUILD_ROOT}%{prefix} maninst=${RPM_BUILD_ROOT}%{prefix}/share/man install
strip ${RPM_BUILD_ROOT}%{prefix}/bin/%{name}
gzip -9nf ${RPM_BUILD_ROOT}%{_mandir}/man1/%{name}.1

%clean
rm -rf ${RPM_BUILD_ROOT}

%files
%defattr(-,root,root)
%doc htmldoc/*
%doc %{_mandir}/man1/*
%{prefix}/bin/*

%changelog
* Fri Apr 04 2003 Edgar Aichinger <eaiching@t0.or.at>
- updated to latest version, now based on tidylib
- removed obsoleted futime() patch
- added tab2space to binary rpm
- repacked src tarball (missing ./tidy directory)

* Mon Sep 02 2002 Edgar Aichinger <eaiching@t0.or.at>
- updated to latest beta version (dated 02-08-22)
- include whole docs in binary rpm, not just quickref.html
- repacked source tarball (missing ./tidy directory in sourceforge dist)

* Wed Mar 13 2002 Edgar Aichinger <eaiching@t0.or.at>
- forgot to add Distribution, Vendor, Packager, Summary(de) to new specfile

* Tue Mar 12 2002 Edgar Aichinger <eaiching@t0.or.at>
- updated to latest version from tidy.sourceforge.net

* Sun Nov 12 2000 Edgar Aichinger <eaiching@t0.or.at>
- new version (sorry for the delay...)
- now this rpm version also can preserve filetimes
  (pointed out by Martin-Eric Racine, thanks to Arnaud Bercegeay for the code)

* Tue Jul 11 2000 Edgar Aichinger <eaiching@t0.or.at>
- updated to latest version

* Fri May 05 2000 Edgar Aichinger <eaiching@t0.or.at>
- (latest version)
- config file ~/.tidyrc (platform.h)
- activate getpwnam support in platform.h

* Wed Jan 19 2000 Edgar Aichinger <eaiching@t0.or.at>
- first release for SpareMiNT (latest version)
- manpage now in /usr/share/man

* Sat Nov 13 1999 Edgar Aichinger <eaiching@t0.or.at>
- first release for SpareMiNT 
