" Enable vim-mode (vi-compatible mode can be quite annoying), but only
" for the full-featured version
if has("terminfo")
	set nocompatible 
endif
" Set a smaller timeout to prevent misinterpretation of keys after pressing Esc
set timeoutlen=101
