#!/bin/sh

TMPDIR=/tmp/t
WINDIR=/windows/c/atari

f="$1"
towin="$2"

test "$f" = "" && {
	echo "usage: $0 <filename>" >&2
	exit 1
}

f=`realpath $f`
test -f "$f" || {
	echo "no such file: $f" >&2
	exit 1
}

mkdir -p "$TMPDIR"
rm -rf "$TMPDIR/"*

cd "$TMPDIR" || exit 1

tar xf "$f" || exit 1

if test -f usr/bin/gcc || test -f usr/bin/ld.bfd; then
	prefix="$WINDIR/"
	cp -pvr . "$prefix"
elif test -d usr/m68k-atari-mint*/sys-root || test -d usr/lib/gcc-lib/m68k-atari-mint* || test -d usr/m68k-atari-mint*/lib/ldscripts; then
	if test "$towin" = "win"; then
		prefix="$WINDIR/"
		if test -d usr/lib/gcc-lib/m68k-atari-mint; then
			cp -pvr usr/lib/gcc-lib/m68k-atari-mint/. "$prefix/usr/lib/gcc-lib/m68k-atari-mint/"
		else
			cp -pr usr/m68k-atari-mint*/sys-root/. "$prefix"
		fi
	else
		prefix="/"
	
		#find . -type d | while read f; do
		#	sudo mkdir -p "${prefix}$f"
		#done
		#find . -type l | while read f; do
		#	sudo cp -av "$f" "${prefix}$f"
		#done
		#find . -type f | while read f; do
		#	sudo cp -av "$f" "${prefix}$f"
		#done
		cp -pvr . "$prefix"
	fi
else
	prefix="$WINDIR/"
	cp -pr . "$prefix"
fi

rm -rf "$TMPDIR/"*
