#!/bin/sh

me="$0"
scriptdir=${0%/*}

PACKAGENAME=rpm
VERSION=-4.15.1.1
VERSIONPATCH=

. ${scriptdir}/functions.sh

# this is a squashed patch generated by running "git diff rpm-4.15.x 4.15-mint"
# For a history of the separate mint specific patches, look at
PATCHES="
patches/rpm/rpm-4.15-mint.patch
"
EXTRA_DIST="
patches/automake/mintelf-config.sub
"

POST_INSTALL_SCRIPTS="
patches/rpm/rpm-howto.tar.bz2
patches/rpm/rpm-suse_macros
patches/rpm/rpm-macros.rpmint
patches/rpm/rpm-mint_macros
patches/rpm/rpm-rpmconfigcheck
patches/rpm/rpm-rpmconfigcheck.service
patches/rpm/rpm-rpmsort
patches/rpm/rpm-sysconfig.services-rpm
"

BINFILES="
bin/*
var
${TARGET_SYSCONFDIR#/}
${TARGET_BINDIR#/}/*
${TARGET_PREFIX#/}/lib/rpm
${TARGET_MANDIR#/}/man1/*
${TARGET_PREFIX#/}/share/doc/packages/${PACKAGENAME}
${TARGET_PREFIX#/}/sbin/*
${TARGET_PREFIX#/}/src/packages
"

unpack_archive

cd "$MINT_BUILD_DIR"

rm -rf sqlite
rm -rf beecrypt
rm -f rpmdb/db.h
rm -f m4/libtool.m4
rm -f m4/lt*.m4
autoreconf -fi
# autoreconf may have overwritten config.sub
cp "$BUILD_DIR/patches/automake/mintelf-config.sub" config.sub

sed -e 's/@suse_version@/%{?suse_version}%{!?suse_version:0}/' \
    -e 's/@sles_version@/%{?sles_version}%{!?sles_version:0}/' \
    -e 's/@ul_version@/%{?ul_version}%{!?ul_version:0}/' \
    -e '/@is_opensuse@%{?is_opensuse:nomatch}/d' \
    -e 's/@is_opensuse@/%{?is_opensuse}%{!?is_opensuse:0}/' \
    -e '/@leap_version@%{?leap_version:nomatch}/d' \
    -e 's/@leap_version@/%{?leap_version}%{!?leap_version:0}/' \
  < "${BUILD_DIR}/patches/rpm/rpm-mint_macros" > ${VENDOR}_macros

COMMON_CFLAGS="-O2 -fomit-frame-pointer ${ELF_CFLAGS}"

CONFIGURE_FLAGS="--host=${TARGET} \
	--prefix=${prefix} \
	--mandir=${prefix}/share/man \
	--infodir=${prefix}/share/info \
	--libdir=${prefix}/lib \
	--sysconfdir=${TARGET_SYSCONFDIR} \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--with-rundir=/var/run \
	--with-lua \
	--with-external-db \
	--docdir=${TARGET_PREFIX}/share/doc/packages/${PACKAGENAME} \
	--with-vendor="${VENDOR}" \
	--without-archive \
	--without-selinux \
	--with-crypto=beecrypt \
	--without-internal-beecrypt \
	--without-acl \
	--without-cap \
	--disable-shared \
	--disable-python \
	--disable-plugins \
	--disable-openmp \
"
STACKSIZE="-Wl,-stack,256k"

export PKG_CONFIG_LIBDIR="$prefix/$TARGET/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_LIBDIR"

for CPU in ${ALL_CPUS}; do
	cd "$MINT_BUILD_DIR"

	eval CPU_CFLAGS=\${CPU_CFLAGS_$CPU}
	eval multilibdir=\${CPU_LIBDIR_$CPU}
	eval multilibexecdir=\${CPU_LIBEXECDIR_$CPU}
	CFLAGS="$CPU_CFLAGS $COMMON_CFLAGS -DLUA_COMPAT_MODULE=1" \
	LDFLAGS="$CPU_CFLAGS $COMMON_CFLAGS ${STACKSIZE}" \
	./configure ${CONFIGURE_FLAGS} \
		--libdir='${exec_prefix}/lib'$multilibdir
	: hack_lto_cflags

	sed -i 's/-lpthread//' config.status
	./config.status
	echo "#undef HAVE_PTHREAD_H" >> config.h

	rm -rf autom4te.cache config.h.in.orig

	${MAKE} || exit 1
	buildroot="${THISPKG_DIR}${sysroot}"
	_fillupdir=/var/adm/fillup-templates
	
	${MAKE} DESTDIR="${buildroot}" install
	mkdir -p ${buildroot}/bin
	ln -sf ${TARGET_PREFIX}/bin/rpm ${buildroot}/bin/rpm
	ln -sf ../db4/db.h ${buildroot}${TARGET_PREFIX}/include/rpm/db.h
	mkdir -p ${buildroot}/usr/sbin
	mkdir -p ${buildroot}/var/run

	install -m 755 ${BUILD_DIR}/patches/rpm/rpm-rpmconfigcheck ${buildroot}/usr/sbin/rpmconfigcheck
	mkdir -p ${buildroot}/usr/lib/systemd/system
	install -m 644 ${BUILD_DIR}/patches/rpm/rpm-rpmconfigcheck.service ${buildroot}/usr/lib/systemd/system/rpmconfigcheck.service
	cp -a ${VENDOR}_macros ${buildroot}/usr/lib/rpm
	mkdir -p ${buildroot}/usr/lib/rpm/macros.d
	mkdir -p ${buildroot}/usr/lib/rpm/${VENDOR}
	ln -sf ../${VENDOR}_macros ${buildroot}/usr/lib/rpm/${VENDOR}/macros
	for d in BUILD RPMS SOURCES SPECS SRPMS BUILDROOT ; do
	  mkdir -p ${buildroot}/usr/src/packages/$d
	  chmod 755 ${buildroot}/usr/src/packages/$d
	done
	for d in ${buildroot}/usr/lib/rpm/platform/*-mint/macros ; do
	  dd=${d%%-mint/macros}
	  dd=${dd##*/}
	  mkdir -p ${buildroot}/usr/src/packages/RPMS/$dd
	  chmod 755 ${buildroot}/usr/src/packages/RPMS/$dd
	done
	mkdir -p ${buildroot}/usr/lib/sysimage/rpm
	mkdir -p ${buildroot}/var/lib/rpm
	chmod 755 doc/manual
	mkdir -p ${buildroot}${TARGET_PREFIX}/share/doc/packages/${PACKAGENAME}
	cp -pvr doc/manual ${buildroot}${TARGET_PREFIX}/share/doc/packages/${PACKAGENAME}
	rm -rf ${buildroot}${TARGET_PREFIX}/share/doc/packages/${PACKAGENAME}/manual/Makefile*
	( cd ${buildroot}${TARGET_PREFIX}/share/doc/packages/${PACKAGENAME}/ ;
	  tar xvf ${BUILD_DIR}/patches/rpm/rpm-howto.tar.bz2
	)
	  
	rm -f ${buildroot}/usr/lib/rpmpopt
	rm -rf ${buildroot}/usr/share/man/{fr,ja,ko,pl,ru,sk}
	mkdir -p ${buildroot}${_fillupdir}
	install -c -m 644 ${BUILD_DIR}/patches/rpm/rpm-sysconfig.services-rpm ${buildroot}${_fillupdir}/sysconfig.services-rpm
	rm -f ${buildroot}/usr/lib/rpm/cpanflute ${buildroot}/usr/lib/rpm/cpanflute2
	install -m 755 ${BUILD_DIR}/patches/rpm/rpm-rpmsort ${buildroot}/usr/lib/rpm/rpmsort
	install -m 755 scripts/find-supplements{,.ksyms} ${buildroot}/usr/lib/rpm
	: install -m 755 scripts/firmware.prov ${buildroot}/usr/lib/rpm
	install -m 755 scripts/debuginfo.prov ${buildroot}/usr/lib/rpm
	rm -f ${buildroot}/usr/lib/locale ${buildroot}/usr/lib/rpmrc
	mkdir -p ${buildroot}/etc/rpm
	chmod 755 ${buildroot}/etc/rpm
# remove some nonsense or non-working scripts
	pushd ${buildroot}/usr/lib/rpm/
	for f in rpm2cpio.sh rpm.daily rpmdiff* rpm.log rpm.xinetd freshen.sh u_pkg.sh \
	         magic magic.mgc magic.mime* rpmfile *.pl javadeps brp-redhat \
	         brp-strip-static-archive vpkg-provides*.sh http.req sql.req tcl.req \
	         brp-sparc64-linux brp-strip-comment-note brp-java-gcjcompile
	do
	    rm -f $f
	done
	popd
	rm -rf ${buildroot}/${TARGET_LIBDIR}/python*
	sh ${buildroot}/usr/lib/rpm/find-lang.sh ${buildroot} rpm
	
	${MAKE} clean >/dev/null

	rm -f ${THISPKG_DIR}${sysroot}${TARGET_LIBDIR}$multilibdir/charset.alias

	make_bin_archive $CPU
done

move_prefix
configured_prefix="${prefix}"
copy_pkg_configs

make_archives
