#!/bin/sh
export GOOS=mint
export GOARCH=m68k
export GOENV=off
export GCCGO=m68k-atari-mintelf-gccgo
export AR=m68k-atari-mintelf-ar
export CC=m68k-atari-mintelf-gcc
export CXX=m68k-atari-mintelf-g++
export GOCACHE=$HOME/.cache/m68k-atari-mintelf-go-build
export GOMODCACHE=/dev/null
export GOGCCFLAGS="-fmessage-length=0"
exec go "$@"
