%define pkgname rpm

%rpmint_header

Summary       : The Red Hat package management system
%if "%{buildtype}" == "cross"
Name:           cross-mint-%{pkgname}
%else
Name:           %{pkgname}
%endif
Version       : 4.15.1.1
Release       : 2
License       : GPL-2.0-or-later
Group         : System/Packages

%rpmint_essential
%if "%{buildtype}" == "cross"
BuildRequires : cross-mint-gettext-runtime
BuildRequires : cross-mint-db-devel
BuildRequires : cross-mint-bzip2-devel
BuildRequires : cross-mint-popt-devel
BuildRequires : cross-mint-liblzma5
BuildRequires : cross-mint-lua-devel
BuildRequires : cross-mint-zlib-devel
BuildRequires : cross-mint-zstd-devel
%else
BuildRequires : db-devel
%endif

Packager      : Thorsten Otto <admin@tho-otto.de>
URL           : http://www.rpm.org/

Prefix        : %{_rpmint_target_prefix}
Docdir        : %{_isysroot}%{_rpmint_target_prefix}/share/doc
BuildRoot     : %{_tmppath}/%{name}-root

Source0: http://ftp.rpm.org/releases/rpm-4.15.x/%{pkgname}-%{version}.tar.xz
Source1: patches/automake/mintelf-config.sub
Source2: patches/rpm/rpm-howto.tar.bz2
Source3: patches/rpm/rpm-suse_macros
Source4: patches/rpm/rpm-macros.rpmint
Source5: patches/rpm/rpm-mint_macros
Source6: patches/rpm/rpm-rpmconfigcheck
Source7: patches/rpm/rpm-rpmconfigcheck.service
Source8: patches/rpm/rpm-rpmsort
Source9: patches/rpm/rpm-sysconfig.services-rpm
# this is a squashed patch generated by running "git diff rpm-4.15.x 4.15-mint"
# For a history of the separate mint specific patches, look at
Patch0:  patches/%{pkgname}/rpm-4.15-mint.patch

%rpmint_build_arch


%description

The RPM Package Manager (RPM) is a powerful command line driven
package management system capable of installing, uninstalling,
verifying, querying, and updating software packages.  Each software
package consists of an archive of files along with information about
the package like its version, a description, etc.

%package devel
Summary       : Development files for applications which will manipulate RPM packages.
Group         : Development/Libraries
Requires      : %{name} = %{version}
%if "%{buildtype}" == "cross"
Requires      : cross-mint-popt
%else
Requires      : popt
%endif

%description devel
This package contains the RPM C library and header files.  These
development files will simplify the process of writing programs which
manipulate RPM packages and databases. These files are intended to
simplify the process of creating graphical package managers or any
other tools that need an intimate knowledge of RPM packages in order
to function.

This package should be installed if you want to develop programs that
will manipulate RPM packages and databases.

%package build
Summary       : Tools and Scripts to create rpm packages
Group         : Development/Tools
Requires      : %{name} = %{version}

%description build
This package contains scripts and executable programs that are used to
build packages using RPM.


%prep
[ "%{buildroot}" == "/" -o "%{buildroot}" == "" ] && exit 1
%setup -q -n %{pkgname}-%{version}
%patch0 -p1

rm -rf sqlite
rm -rf beecrypt
rm -f rpmdb/db.h
rm -f m4/libtool.m4
rm -f m4/lt*.m4
autoreconf -fi
# autoreconf may have overwritten config.sub
cp "%{S:1}" config.sub

sed -e 's/@suse_version@/%{?suse_version}%{!?suse_version:0}/' \
    -e 's/@sles_version@/%{?sles_version}%{!?sles_version:0}/' \
    -e 's/@ul_version@/%{?ul_version}%{!?ul_version:0}/' \
    -e '/@is_opensuse@%{?is_opensuse:nomatch}/d' \
    -e 's/@is_opensuse@/%{?is_opensuse}%{!?is_opensuse:0}/' \
    -e '/@leap_version@%{?leap_version:nomatch}/d' \
    -e 's/@leap_version@/%{?leap_version}%{!?leap_version:0}/' \
  < "%{S:5}" > %{vendor}_macros


%build
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%rpmint_cflags

CONFIGURE_FLAGS="--host=${TARGET} \
	--prefix=%{_rpmint_target_prefix} \
	--mandir=%{_rpmint_target_prefix}/share/man \
	--infodir=%{_rpmint_target_prefix}/share/info \
	--libdir=%{_rpmint_target_prefix}/lib \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--with-rundir=/var/run \
	--with-lua \
	--with-external-db \
	--docdir=%{_rpmint_target_prefix}/share/doc/packages/%{pkgname} \
	--with-vendor="%{vendor}" \
	--without-archive \
	--without-selinux \
	--with-crypto=beecrypt \
	--without-internal-beecrypt \
	--without-acl \
	--without-cap \
	--disable-shared \
	--disable-python \
	--disable-plugins \
	--disable-openmp \
"
STACKSIZE="-Wl,-stack,256k"

%define _fillupdir /var/adm/fillup-templates

for CPU in ${ALL_CPUS}; do
	eval CPU_CFLAGS=\${CPU_CFLAGS_$CPU}
	eval multilibdir=\${CPU_LIBDIR_$CPU}
	eval multilibexecdir=\${CPU_LIBEXECDIR_$CPU}

	CFLAGS="$CPU_CFLAGS $COMMON_CFLAGS -DLUA_COMPAT_MODULE=1" \
	LDFLAGS="$CPU_CFLAGS $COMMON_CFLAGS ${STACKSIZE}" \
	./configure ${CONFIGURE_FLAGS} \
		--libdir='${exec_prefix}/lib'$multilibdir
	sed -i 's/-lpthread//' config.status
	./config.status
	echo "#undef HAVE_PTHREAD_H" >> config.h

	rm -rf autom4te.cache config.h.in.orig

	make %{?_smp_mflags}

	buildroot="%{buildroot}%{_rpmint_sysroot}"
	make DESTDIR="${buildroot}" install

	mkdir -p ${buildroot}/bin
	ln -sf ..%{_rpmint_target_prefix}/bin/rpm ${buildroot}/bin/rpm
	ln -sf ../db4/db.h ${buildroot}%{_rpmint_target_prefix}/include/rpm/db.h
	mkdir -p ${buildroot}%{_rpmint_target_prefix}/sbin
	mkdir -p ${buildroot}/var/run

	install -m 755 %{S:6} ${buildroot}%{_rpmint_target_prefix}/sbin/rpmconfigcheck
	: mkdir -p ${buildroot}%{_rpmint_target_prefix}/lib/systemd/system
	: install -m 644 %{S:7} ${buildroot}%{_rpmint_target_prefix}/lib/systemd/system/rpmconfigcheck.service
	cp -a %{vendor}_macros ${buildroot}%{_rpmint_target_prefix}/lib/rpm
	mkdir -p ${buildroot}%{_rpmint_target_prefix}/lib/rpm/macros.d
	mkdir -p ${buildroot}%{_rpmint_target_prefix}/lib/rpm/%{vendor}
	ln -sf ../%{vendor}_macros ${buildroot}%{_rpmint_target_prefix}/lib/rpm/%{vendor}/macros
	for d in BUILD RPMS SOURCES SPECS SRPMS BUILDROOT ; do
	  mkdir -p ${buildroot}/usr/src/packages/$d
	  chmod 755 ${buildroot}/usr/src/packages/$d
	done
	for d in ${buildroot}/usr/lib/rpm/platform/*-mint/macros ; do
	  dd=${d%%-mint/macros}
	  dd=${dd##*/}
	  mkdir -p ${buildroot}/usr/src/packages/RPMS/$dd
	  chmod 755 ${buildroot}/usr/src/packages/RPMS/$dd
	done
	mkdir -p ${buildroot}/usr/lib/sysimage/rpm
	mkdir -p ${buildroot}/var/lib/rpm
	chmod 755 doc/manual
	mkdir -p ${buildroot}%{_rpmint_target_prefix}/share/doc/packages/%{pkgname}
	cp -pvr doc/manual ${buildroot}%{_rpmint_target_prefix}/share/doc/packages/%{pkgname}
	rm -rf ${buildroot}%{_rpmint_target_prefix}/share/doc/packages/%{pkgname}/manual/Makefile*
	( cd ${buildroot}%{_rpmint_target_prefix}/share/doc/packages/%{pkgname}/ ;
	  tar xvf %{S:2}
	)
	  
	rm -f ${buildroot}/usr/lib/rpmpopt
	rm -rf ${buildroot}/usr/share/man/{fr,ja,ko,pl,ru,sk}
	mkdir -p ${buildroot}%{_fillupdir}
	install -c -m 644 %{S:9} ${buildroot}%{_fillupdir}/sysconfig.services-rpm
	rm -f ${buildroot}/usr/lib/rpm/cpanflute ${buildroot}/usr/lib/rpm/cpanflute2
	install -m 755 %{S:8} ${buildroot}/usr/lib/rpm/rpmsort
	install -m 755 scripts/find-supplements{,.ksyms} ${buildroot}/usr/lib/rpm
	: install -m 755 scripts/firmware.prov ${buildroot}/usr/lib/rpm
	install -m 755 scripts/debuginfo.prov ${buildroot}/usr/lib/rpm
	rm -f ${buildroot}/usr/lib/locale ${buildroot}/usr/lib/rpmrc
	mkdir -p ${buildroot}/etc/rpm
	chmod 755 ${buildroot}/etc/rpm
# remove some nonsense or non-working scripts
	pushd ${buildroot}/usr/lib/rpm/
	for f in rpm2cpio.sh rpm.daily rpmdiff* rpm.log rpm.xinetd freshen.sh u_pkg.sh \
	         magic magic.mgc magic.mime* rpmfile *.pl javadeps brp-redhat \
	         brp-strip-static-archive vpkg-provides*.sh http.req sql.req tcl.req \
	         brp-sparc64-linux brp-strip-comment-note brp-java-gcjcompile
	do
	    rm -f $f
	done
	popd
	rm -rf ${buildroot}/%{_rpmint_target_prefix}/lib/python*
	sh ${buildroot}/usr/lib/rpm/find-lang.sh ${buildroot} rpm
	
	# compress manpages
	%rpmint_gzip_docs
	# remove obsolete pkg config files
	%rpmint_remove_pkg_configs

	rm -f ${buildroot}%{_rpmint_target_prefix}/lib$multilibdir/charset.alias

	%if "%{buildtype}" != "cross"
	if test "%{buildtype}" != "$CPU"; then
		rm -f %{buildroot}%{_rpmint_bindir}/*
	fi
	%rpmint_make_bin_archive $CPU
	%else
	%{_rpmint_target_strip} %{buildroot}%{_rpmint_bindir}/* || :
	%endif
	
	make clean
done



%install

%rpmint_cflags

%rpmint_strip_archives

%if "%{buildtype}" == "cross"
configured_prefix="%{_rpmint_target_prefix}"
%rpmint_copy_pkg_configs
%else
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}%{_rpmint_sysroot}
rmdir %{buildroot}%{_rpmint_installdir} || :
rmdir %{buildroot}%{_prefix} 2>/dev/null || :
%endif


%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files
%defattr(-,root,root)
%{_isysroot}/bin/*
%{_isysroot}%{_rpmint_target_prefix}/bin/*
%exclude %{_isysroot}%{_rpmint_target_prefix}/bin/rpmbuild
%{_isysroot}%{_rpmint_target_prefix}/sbin/*
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/macros
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/macros.d/
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/platform
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpm.supp
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpmdb_*
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpmpopt-*
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/mkinstalldirs
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpmrc
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpmsort
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/tgpg
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/%{vendor}/
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/%{vendor}_macros
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/lua/

%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/BUILD
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/SPECS
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/SOURCES
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/SRPMS
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/RPMS
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/BUILDROOT
%dir %{_isysroot}%{_rpmint_target_prefix}/src/packages/RPMS/*
%{_isysroot}%{_fillupdir}/sysconfig.services-rpm

%dir 	%{_isysroot}%{_rpmint_target_prefix}/lib/sysimage
%dir 	%{_isysroot}%{_rpmint_target_prefix}/lib/sysimage/rpm
%ghost	%{_isysroot}/var/lib/rpm

%{_isysroot}%{_rpmint_target_prefix}/share/man/man*/*
%{_isysroot}%{_rpmint_target_prefix}/share/locale/*/*/rpm.mo

%files build
%defattr(-,root,root)
%{_isysroot}%{_rpmint_target_prefix}/bin/rpmbuild
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/pkgconfigdeps.sh
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/elfdeps
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/rpmdeps
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/pythondeps.sh
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/sysvinitdeps.sh
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/pythondistdeps.py
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/libtooldeps.sh
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/brp-*
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/check-*
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/config.guess
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/config.sub
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/*.req
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/*.prov
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/fileattrs/
%{_isysroot}%{_rpmint_target_prefix}/lib/rpm/*find*
%{_isysroot}%{_rpmint_target_prefix}/share/doc/packages/%{pkgname}

%files devel
%defattr(-,root,root)
%{_isysroot}%{_rpmint_target_prefix}/include/*
%{_isysroot}%{_rpmint_target_prefix}/lib/pkgconfig/*.pc
%{_isysroot}%{_rpmint_target_prefix}/lib/*.a
%{_isysroot}%{_rpmint_target_prefix}/lib/*/*.a
%if "%{buildtype}" == "cross"
%{_rpmint_cross_pkgconfigdir}/*.pc
%endif


%changelog
* Fri Mar 24 2023 Thorsten Otto <admin@tho-otto.de>
- RPMint spec file
- Update to version 4.15.1.1

* Thu Oct 11 2001 Frank Naumann <fnaumann@freemint.de>
- updated to 3.0.6
- recompiled against updated MiNTLib, db-lib etc.

* Wed Aug 25 1999 Frank Naumann <fnaumann@freemint.de>
- compressed manpages
- correct Packager and Vendor

