#!/bin/sh

gmp='https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz'
mpfr='https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.4.tar.xz'
mpc='ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz'
isl='http://isl.gforge.inria.fr/isl-0.18.tar.xz'

archives="$gmp $mpfr $mpc $isl"

die() {
    echo "error: $@" >&2
    exit 1
}

if type wget > /dev/null ; then
  fetch='wget'
else
  fetch='curl -LO'
fi
[ -e ./gcc/BASE-VER ] || die "You must run this script in the top-level GCC source directory"

srcdir=.
test "$1" != "" && srcdir="$1"

for ar in $archives
do
    file=${ar##*/}
    [ -e "${srcdir}/${file}" ]                                               \
        || ${fetch} --no-verbose -O "${srcdir}/${file}" "${ar}"       \
        || die "Cannot download ${ar}"
    
    dir="${file%.tar*}"
    [ -d "${dir}" ]                                          \
        || tar -xf "${srcdir}/${file}"                           \
        || die "Cannot extract package from ${srcdir}/${file}"

    target="${dir}/"
    linkname="${dir%-*}"
    [ -e "${linkname}" ]                                                      \
        || ln -s "${target}" "${linkname}"                                    \
        || die "Cannot create symbolic link ${linkname} --> ${target}"

done
