<?php

class License {
	public static $spdx_org = 'https://spdx.org/licenses/';

	public static $licenses = array(
		'0BSD' => [ 'id' => '0BSD', 'fullname' => 'BSD Zero Clause License', 'href' => '0BSD.html', 'free' => false, 'osi' => true ],
		'AAL' => [ 'id' => 'AAL', 'fullname' => 'Attribution Assurance License', 'href' => 'AAL.html', 'free' => false, 'osi' => true ],
		'Abstyles' => [ 'id' => 'Abstyles', 'fullname' => 'Abstyles License', 'href' => 'Abstyles.html', 'free' => false, 'osi' => false ],
		'AdaCore-doc' => [ 'id' => 'AdaCore-doc', 'fullname' => 'AdaCore Doc License', 'href' => 'AdaCore-doc.html', 'free' => false, 'osi' => false ],
		'Adobe-2006' => [ 'id' => 'Adobe-2006', 'fullname' => 'Adobe Systems Incorporated Source Code License Agreement', 'href' => 'Adobe-2006.html', 'free' => false, 'osi' => false ],
		'Adobe-Glyph' => [ 'id' => 'Adobe-Glyph', 'fullname' => 'Adobe Glyph List License', 'href' => 'Adobe-Glyph.html', 'free' => false, 'osi' => false ],
		'ADSL' => [ 'id' => 'ADSL', 'fullname' => 'Amazon Digital Services License', 'href' => 'ADSL.html', 'free' => false, 'osi' => false ],
		'AFL-1.1' => [ 'id' => 'AFL-1.1', 'fullname' => 'Academic Free License v1.1', 'href' => 'AFL-1.1.html', 'free' => true, 'osi' => true ],
		'AFL-1.2' => [ 'id' => 'AFL-1.2', 'fullname' => 'Academic Free License v1.2', 'href' => 'AFL-1.2.html', 'free' => true, 'osi' => true ],
		'AFL-2.0' => [ 'id' => 'AFL-2.0', 'fullname' => 'Academic Free License v2.0', 'href' => 'AFL-2.0.html', 'free' => true, 'osi' => true ],
		'AFL-2.1' => [ 'id' => 'AFL-2.1', 'fullname' => 'Academic Free License v2.1', 'href' => 'AFL-2.1.html', 'free' => true, 'osi' => true ],
		'AFL-3.0' => [ 'id' => 'AFL-3.0', 'fullname' => 'Academic Free License v3.0', 'href' => 'AFL-3.0.html', 'free' => true, 'osi' => true ],
		'Afmparse' => [ 'id' => 'Afmparse', 'fullname' => 'Afmparse License', 'href' => 'Afmparse.html', 'free' => false, 'osi' => false ],
		'AGPL-1.0-only' => [ 'id' => 'AGPL-1.0-only', 'fullname' => 'Affero General Public License v1.0 only', 'href' => 'AGPL-1.0-only.html', 'free' => false, 'osi' => false ],
		'AGPL-1.0-or-later' => [ 'id' => 'AGPL-1.0-or-later', 'fullname' => 'Affero General Public License v1.0 or later', 'href' => 'AGPL-1.0-or-later.html', 'free' => false, 'osi' => false ],
		'AGPL-3.0-only' => [ 'id' => 'AGPL-3.0-only', 'fullname' => 'GNU Affero General Public License v3.0 only', 'href' => 'AGPL-3.0-only.html', 'free' => true, 'osi' => true ],
		'AGPL-3.0-or-later' => [ 'id' => 'AGPL-3.0-or-later', 'fullname' => 'GNU Affero General Public License v3.0 or later', 'href' => 'AGPL-3.0-or-later.html', 'free' => true, 'osi' => true ],
		'Aladdin' => [ 'id' => 'Aladdin', 'fullname' => 'Aladdin Free Public License', 'href' => 'Aladdin.html', 'free' => false, 'osi' => false ],
		'AMDPLPA' => [ 'id' => 'AMDPLPA', 'fullname' => 'AMD\'s plpa_map.c License', 'href' => 'AMDPLPA.html', 'free' => false, 'osi' => false ],
		'AML' => [ 'id' => 'AML', 'fullname' => 'Apple MIT License', 'href' => 'AML.html', 'free' => false, 'osi' => false ],
		'AMPAS' => [ 'id' => 'AMPAS', 'fullname' => 'Academy of Motion Picture Arts and Sciences BSD', 'href' => 'AMPAS.html', 'free' => false, 'osi' => false ],
		'ANTLR-PD' => [ 'id' => 'ANTLR-PD', 'fullname' => 'ANTLR Software Rights Notice', 'href' => 'ANTLR-PD.html', 'free' => false, 'osi' => false ],
		'ANTLR-PD-fallback' => [ 'id' => 'ANTLR-PD-fallback', 'fullname' => 'ANTLR Software Rights Notice with license fallback', 'href' => 'ANTLR-PD-fallback.html', 'free' => false, 'osi' => false ],
		'Apache-1.0' => [ 'id' => 'Apache-1.0', 'fullname' => 'Apache License 1.0', 'href' => 'Apache-1.0.html', 'free' => true, 'osi' => false ],
		'Apache-1.1' => [ 'id' => 'Apache-1.1', 'fullname' => 'Apache License 1.1', 'href' => 'Apache-1.1.html', 'free' => true, 'osi' => true ],
		'Apache-2.0' => [ 'id' => 'Apache-2.0', 'fullname' => 'Apache License 2.0', 'href' => 'Apache-2.0.html', 'free' => true, 'osi' => true ],
		'APAFML' => [ 'id' => 'APAFML', 'fullname' => 'Adobe Postscript AFM License', 'href' => 'APAFML.html', 'free' => false, 'osi' => false ],
		'APL-1.0' => [ 'id' => 'APL-1.0', 'fullname' => 'Adaptive Public License 1.0', 'href' => 'APL-1.0.html', 'free' => false, 'osi' => true ],
		'App-s2p' => [ 'id' => 'App-s2p', 'fullname' => 'App::s2p License', 'href' => 'App-s2p.html', 'free' => false, 'osi' => false ],
		'APSL-1.0' => [ 'id' => 'APSL-1.0', 'fullname' => 'Apple Public Source License 1.0', 'href' => 'APSL-1.0.html', 'free' => false, 'osi' => true ],
		'APSL-1.1' => [ 'id' => 'APSL-1.1', 'fullname' => 'Apple Public Source License 1.1', 'href' => 'APSL-1.1.html', 'free' => false, 'osi' => true ],
		'APSL-1.2' => [ 'id' => 'APSL-1.2', 'fullname' => 'Apple Public Source License 1.2', 'href' => 'APSL-1.2.html', 'free' => false, 'osi' => true ],
		'APSL-2.0' => [ 'id' => 'APSL-2.0', 'fullname' => 'Apple Public Source License 2.0', 'href' => 'APSL-2.0.html', 'free' => true, 'osi' => true ],
		'Arphic-1999' => [ 'id' => 'Arphic-1999', 'fullname' => 'Arphic Public License', 'href' => 'Arphic-1999.html', 'free' => false, 'osi' => false ],
		'Artistic-1.0' => [ 'id' => 'Artistic-1.0', 'fullname' => 'Artistic License 1.0', 'href' => 'Artistic-1.0.html', 'free' => false, 'osi' => true ],
		'Artistic-1.0-cl8' => [ 'id' => 'Artistic-1.0-cl8', 'fullname' => 'Artistic License 1.0 w/clause 8', 'href' => 'Artistic-1.0-cl8.html', 'free' => false, 'osi' => true ],
		'Artistic-1.0-Perl' => [ 'id' => 'Artistic-1.0-Perl', 'fullname' => 'Artistic License 1.0 (Perl)', 'href' => 'Artistic-1.0-Perl.html', 'free' => false, 'osi' => true ],
		'Artistic-2.0' => [ 'id' => 'Artistic-2.0', 'fullname' => 'Artistic License 2.0', 'href' => 'Artistic-2.0.html', 'free' => true, 'osi' => true ],
		'Baekmuk' => [ 'id' => 'Baekmuk', 'fullname' => 'Baekmuk License', 'href' => 'Baekmuk.html', 'free' => false, 'osi' => false ],
		'Bahyph' => [ 'id' => 'Bahyph', 'fullname' => 'Bahyph License', 'href' => 'Bahyph.html', 'free' => false, 'osi' => false ],
		'Barr' => [ 'id' => 'Barr', 'fullname' => 'Barr License', 'href' => 'Barr.html', 'free' => false, 'osi' => false ],
		'Beerware' => [ 'id' => 'Beerware', 'fullname' => 'Beerware License', 'href' => 'Beerware.html', 'free' => false, 'osi' => false ],
		'Bitstream-Charter' => [ 'id' => 'Bitstream-Charter', 'fullname' => 'Bitstream Charter Font License', 'href' => 'Bitstream-Charter.html', 'free' => false, 'osi' => false ],
		'Bitstream-Vera' => [ 'id' => 'Bitstream-Vera', 'fullname' => 'Bitstream Vera Font License', 'href' => 'Bitstream-Vera.html', 'free' => false, 'osi' => false ],
		'BitTorrent-1.0' => [ 'id' => 'BitTorrent-1.0', 'fullname' => 'BitTorrent Open Source License v1.0', 'href' => 'BitTorrent-1.0.html', 'free' => false, 'osi' => false ],
		'BitTorrent-1.1' => [ 'id' => 'BitTorrent-1.1', 'fullname' => 'BitTorrent Open Source License v1.1', 'href' => 'BitTorrent-1.1.html', 'free' => true, 'osi' => false ],
		'blessing' => [ 'id' => 'blessing', 'fullname' => 'SQLite Blessing', 'href' => 'blessing.html', 'free' => false, 'osi' => false ],
		'BlueOak-1.0.0' => [ 'id' => 'BlueOak-1.0.0', 'fullname' => 'Blue Oak Model License 1.0.0', 'href' => 'BlueOak-1.0.0.html', 'free' => false, 'osi' => false ],
		'Borceux' => [ 'id' => 'Borceux', 'fullname' => 'Borceux license', 'href' => 'Borceux.html', 'free' => false, 'osi' => false ],
		'Brian-Gladman-3-Clause' => [ 'id' => 'Brian-Gladman-3-Clause', 'fullname' => 'Brian Gladman 3-Clause License', 'href' => 'Brian-Gladman-3-Clause.html', 'free' => false, 'osi' => false ],
		'BSD-1-Clause' => [ 'id' => 'BSD-1-Clause', 'fullname' => 'BSD 1-Clause License', 'href' => 'BSD-1-Clause.html', 'free' => false, 'osi' => true ],
		'BSD-2-Clause' => [ 'id' => 'BSD-2-Clause', 'fullname' => 'BSD 2-Clause "Simplified" License', 'href' => 'BSD-2-Clause.html', 'free' => true, 'osi' => true ],
		'BSD-2-Clause-Patent' => [ 'id' => 'BSD-2-Clause-Patent', 'fullname' => 'BSD-2-Clause Plus Patent License', 'href' => 'BSD-2-Clause-Patent.html', 'free' => false, 'osi' => true ],
		'BSD-2-Clause-Views' => [ 'id' => 'BSD-2-Clause-Views', 'fullname' => 'BSD 2-Clause with views sentence', 'href' => 'BSD-2-Clause-Views.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause' => [ 'id' => 'BSD-3-Clause', 'fullname' => 'BSD 3-Clause "New" or "Revised" License', 'href' => 'BSD-3-Clause.html', 'free' => true, 'osi' => true ],
		'BSD-3-Clause-Attribution' => [ 'id' => 'BSD-3-Clause-Attribution', 'fullname' => 'BSD with attribution', 'href' => 'BSD-3-Clause-Attribution.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-Clear' => [ 'id' => 'BSD-3-Clause-Clear', 'fullname' => 'BSD 3-Clause Clear License', 'href' => 'BSD-3-Clause-Clear.html', 'free' => true, 'osi' => false ],
		'BSD-3-Clause-LBNL' => [ 'id' => 'BSD-3-Clause-LBNL', 'fullname' => 'Lawrence Berkeley National Labs BSD variant license', 'href' => 'BSD-3-Clause-LBNL.html', 'free' => false, 'osi' => true ],
		'BSD-3-Clause-Modification' => [ 'id' => 'BSD-3-Clause-Modification', 'fullname' => 'BSD 3-Clause Modification', 'href' => 'BSD-3-Clause-Modification.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-No-Military-License' => [ 'id' => 'BSD-3-Clause-No-Military-License', 'fullname' => 'BSD 3-Clause No Military License', 'href' => 'BSD-3-Clause-No-Military-License.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-No-Nuclear-License' => [ 'id' => 'BSD-3-Clause-No-Nuclear-License', 'fullname' => 'BSD 3-Clause No Nuclear License', 'href' => 'BSD-3-Clause-No-Nuclear-License.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-No-Nuclear-License-2014' => [ 'id' => 'BSD-3-Clause-No-Nuclear-License-2014', 'fullname' => 'BSD 3-Clause No Nuclear License 2014', 'href' => 'BSD-3-Clause-No-Nuclear-License-2014.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-No-Nuclear-Warranty' => [ 'id' => 'BSD-3-Clause-No-Nuclear-Warranty', 'fullname' => 'BSD 3-Clause No Nuclear Warranty', 'href' => 'BSD-3-Clause-No-Nuclear-Warranty.html', 'free' => false, 'osi' => false ],
		'BSD-3-Clause-Open-MPI' => [ 'id' => 'BSD-3-Clause-Open-MPI', 'fullname' => 'BSD 3-Clause Open MPI variant', 'href' => 'BSD-3-Clause-Open-MPI.html', 'free' => false, 'osi' => false ],
		'BSD-4-Clause' => [ 'id' => 'BSD-4-Clause', 'fullname' => 'BSD 4-Clause "Original" or "Old" License', 'href' => 'BSD-4-Clause.html', 'free' => true, 'osi' => false ],
		'BSD-4-Clause-Shortened' => [ 'id' => 'BSD-4-Clause-Shortened', 'fullname' => 'BSD 4 Clause Shortened', 'href' => 'BSD-4-Clause-Shortened.html', 'free' => false, 'osi' => false ],
		'BSD-4-Clause-UC' => [ 'id' => 'BSD-4-Clause-UC', 'fullname' => 'BSD-4-Clause (University of California-Specific)', 'href' => 'BSD-4-Clause-UC.html', 'free' => false, 'osi' => false ],
		'BSD-4.3RENO' => [ 'id' => 'BSD-4.3RENO', 'fullname' => 'BSD 4.3 RENO License', 'href' => 'BSD-4.3RENO.html', 'free' => false, 'osi' => false ],
		'BSD-4.3TAHOE' => [ 'id' => 'BSD-4.3TAHOE', 'fullname' => 'BSD 4.3 TAHOE License', 'href' => 'BSD-4.3TAHOE.html', 'free' => false, 'osi' => false ],
		'BSD-Advertising-Acknowledgement' => [ 'id' => 'BSD-Advertising-Acknowledgement', 'fullname' => 'BSD Advertising Acknowledgement License', 'href' => 'BSD-Advertising-Acknowledgement.html', 'free' => false, 'osi' => false ],
		'BSD-Attribution-HPND-disclaimer' => [ 'id' => 'BSD-Attribution-HPND-disclaimer', 'fullname' => 'BSD with Attribution and HPND disclaimer', 'href' => 'BSD-Attribution-HPND-disclaimer.html', 'free' => false, 'osi' => false ],
		'BSD-Protection' => [ 'id' => 'BSD-Protection', 'fullname' => 'BSD Protection License', 'href' => 'BSD-Protection.html', 'free' => false, 'osi' => false ],
		'BSD-Source-Code' => [ 'id' => 'BSD-Source-Code', 'fullname' => 'BSD Source Code Attribution', 'href' => 'BSD-Source-Code.html', 'free' => false, 'osi' => false ],
		'BSL-1.0' => [ 'id' => 'BSL-1.0', 'fullname' => 'Boost Software License 1.0', 'href' => 'BSL-1.0.html', 'free' => true, 'osi' => true ],
		'BUSL-1.1' => [ 'id' => 'BUSL-1.1', 'fullname' => 'Business Source License 1.1', 'href' => 'BUSL-1.1.html', 'free' => false, 'osi' => false ],
		'bzip2-1.0.6' => [ 'id' => 'bzip2-1.0.6', 'fullname' => 'bzip2 and libbzip2 License v1.0.6', 'href' => 'bzip2-1.0.6.html', 'free' => false, 'osi' => false ],
		'C-UDA-1.0' => [ 'id' => 'C-UDA-1.0', 'fullname' => 'Computational Use of Data Agreement v1.0', 'href' => 'C-UDA-1.0.html', 'free' => false, 'osi' => false ],
		'CAL-1.0' => [ 'id' => 'CAL-1.0', 'fullname' => 'Cryptographic Autonomy License 1.0', 'href' => 'CAL-1.0.html', 'free' => false, 'osi' => true ],
		'CAL-1.0-Combined-Work-Exception' => [ 'id' => 'CAL-1.0-Combined-Work-Exception', 'fullname' => 'Cryptographic Autonomy License 1.0 (Combined Work Exception)', 'href' => 'CAL-1.0-Combined-Work-Exception.html', 'free' => false, 'osi' => true ],
		'Caldera' => [ 'id' => 'Caldera', 'fullname' => 'Caldera License', 'href' => 'Caldera.html', 'free' => false, 'osi' => false ],
		'CATOSL-1.1' => [ 'id' => 'CATOSL-1.1', 'fullname' => 'Computer Associates Trusted Open Source License 1.1', 'href' => 'CATOSL-1.1.html', 'free' => false, 'osi' => true ],
		'CC-BY-1.0' => [ 'id' => 'CC-BY-1.0', 'fullname' => 'Creative Commons Attribution 1.0 Generic', 'href' => 'CC-BY-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-2.0' => [ 'id' => 'CC-BY-2.0', 'fullname' => 'Creative Commons Attribution 2.0 Generic', 'href' => 'CC-BY-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-2.5' => [ 'id' => 'CC-BY-2.5', 'fullname' => 'Creative Commons Attribution 2.5 Generic', 'href' => 'CC-BY-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-2.5-AU' => [ 'id' => 'CC-BY-2.5-AU', 'fullname' => 'Creative Commons Attribution 2.5 Australia', 'href' => 'CC-BY-2.5-AU.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0' => [ 'id' => 'CC-BY-3.0', 'fullname' => 'Creative Commons Attribution 3.0 Unported', 'href' => 'CC-BY-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0-AT' => [ 'id' => 'CC-BY-3.0-AT', 'fullname' => 'Creative Commons Attribution 3.0 Austria', 'href' => 'CC-BY-3.0-AT.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0-DE' => [ 'id' => 'CC-BY-3.0-DE', 'fullname' => 'Creative Commons Attribution 3.0 Germany', 'href' => 'CC-BY-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0-IGO' => [ 'id' => 'CC-BY-3.0-IGO', 'fullname' => 'Creative Commons Attribution 3.0 IGO', 'href' => 'CC-BY-3.0-IGO.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0-NL' => [ 'id' => 'CC-BY-3.0-NL', 'fullname' => 'Creative Commons Attribution 3.0 Netherlands', 'href' => 'CC-BY-3.0-NL.html', 'free' => false, 'osi' => false ],
		'CC-BY-3.0-US' => [ 'id' => 'CC-BY-3.0-US', 'fullname' => 'Creative Commons Attribution 3.0 United States', 'href' => 'CC-BY-3.0-US.html', 'free' => false, 'osi' => false ],
		'CC-BY-4.0' => [ 'id' => 'CC-BY-4.0', 'fullname' => 'Creative Commons Attribution 4.0 International', 'href' => 'CC-BY-4.0.html', 'free' => true, 'osi' => false ],
		'CC-BY-NC-1.0' => [ 'id' => 'CC-BY-NC-1.0', 'fullname' => 'Creative Commons Attribution Non Commercial 1.0 Generic', 'href' => 'CC-BY-NC-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-2.0' => [ 'id' => 'CC-BY-NC-2.0', 'fullname' => 'Creative Commons Attribution Non Commercial 2.0 Generic', 'href' => 'CC-BY-NC-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-2.5' => [ 'id' => 'CC-BY-NC-2.5', 'fullname' => 'Creative Commons Attribution Non Commercial 2.5 Generic', 'href' => 'CC-BY-NC-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-3.0' => [ 'id' => 'CC-BY-NC-3.0', 'fullname' => 'Creative Commons Attribution Non Commercial 3.0 Unported', 'href' => 'CC-BY-NC-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-3.0-DE' => [ 'id' => 'CC-BY-NC-3.0-DE', 'fullname' => 'Creative Commons Attribution Non Commercial 3.0 Germany', 'href' => 'CC-BY-NC-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-4.0' => [ 'id' => 'CC-BY-NC-4.0', 'fullname' => 'Creative Commons Attribution Non Commercial 4.0 International', 'href' => 'CC-BY-NC-4.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-1.0' => [ 'id' => 'CC-BY-NC-ND-1.0', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic', 'href' => 'CC-BY-NC-ND-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-2.0' => [ 'id' => 'CC-BY-NC-ND-2.0', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic', 'href' => 'CC-BY-NC-ND-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-2.5' => [ 'id' => 'CC-BY-NC-ND-2.5', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic', 'href' => 'CC-BY-NC-ND-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-3.0' => [ 'id' => 'CC-BY-NC-ND-3.0', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported', 'href' => 'CC-BY-NC-ND-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-3.0-DE' => [ 'id' => 'CC-BY-NC-ND-3.0-DE', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany', 'href' => 'CC-BY-NC-ND-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-3.0-IGO' => [ 'id' => 'CC-BY-NC-ND-3.0-IGO', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO', 'href' => 'CC-BY-NC-ND-3.0-IGO.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-ND-4.0' => [ 'id' => 'CC-BY-NC-ND-4.0', 'fullname' => 'Creative Commons Attribution Non Commercial No Derivatives 4.0 International', 'href' => 'CC-BY-NC-ND-4.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-1.0' => [ 'id' => 'CC-BY-NC-SA-1.0', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 1.0 Generic', 'href' => 'CC-BY-NC-SA-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-2.0' => [ 'id' => 'CC-BY-NC-SA-2.0', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 2.0 Generic', 'href' => 'CC-BY-NC-SA-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-2.0-DE' => [ 'id' => 'CC-BY-NC-SA-2.0-DE', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 2.0 Germany', 'href' => 'CC-BY-NC-SA-2.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-2.0-FR' => [ 'id' => 'CC-BY-NC-SA-2.0-FR', 'fullname' => 'Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France', 'href' => 'CC-BY-NC-SA-2.0-FR.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-2.0-UK' => [ 'id' => 'CC-BY-NC-SA-2.0-UK', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales', 'href' => 'CC-BY-NC-SA-2.0-UK.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-2.5' => [ 'id' => 'CC-BY-NC-SA-2.5', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 2.5 Generic', 'href' => 'CC-BY-NC-SA-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-3.0' => [ 'id' => 'CC-BY-NC-SA-3.0', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 3.0 Unported', 'href' => 'CC-BY-NC-SA-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-3.0-DE' => [ 'id' => 'CC-BY-NC-SA-3.0-DE', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 3.0 Germany', 'href' => 'CC-BY-NC-SA-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-3.0-IGO' => [ 'id' => 'CC-BY-NC-SA-3.0-IGO', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 3.0 IGO', 'href' => 'CC-BY-NC-SA-3.0-IGO.html', 'free' => false, 'osi' => false ],
		'CC-BY-NC-SA-4.0' => [ 'id' => 'CC-BY-NC-SA-4.0', 'fullname' => 'Creative Commons Attribution Non Commercial Share Alike 4.0 International', 'href' => 'CC-BY-NC-SA-4.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-1.0' => [ 'id' => 'CC-BY-ND-1.0', 'fullname' => 'Creative Commons Attribution No Derivatives 1.0 Generic', 'href' => 'CC-BY-ND-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-2.0' => [ 'id' => 'CC-BY-ND-2.0', 'fullname' => 'Creative Commons Attribution No Derivatives 2.0 Generic', 'href' => 'CC-BY-ND-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-2.5' => [ 'id' => 'CC-BY-ND-2.5', 'fullname' => 'Creative Commons Attribution No Derivatives 2.5 Generic', 'href' => 'CC-BY-ND-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-3.0' => [ 'id' => 'CC-BY-ND-3.0', 'fullname' => 'Creative Commons Attribution No Derivatives 3.0 Unported', 'href' => 'CC-BY-ND-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-3.0-DE' => [ 'id' => 'CC-BY-ND-3.0-DE', 'fullname' => 'Creative Commons Attribution No Derivatives 3.0 Germany', 'href' => 'CC-BY-ND-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-ND-4.0' => [ 'id' => 'CC-BY-ND-4.0', 'fullname' => 'Creative Commons Attribution No Derivatives 4.0 International', 'href' => 'CC-BY-ND-4.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-1.0' => [ 'id' => 'CC-BY-SA-1.0', 'fullname' => 'Creative Commons Attribution Share Alike 1.0 Generic', 'href' => 'CC-BY-SA-1.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-2.0' => [ 'id' => 'CC-BY-SA-2.0', 'fullname' => 'Creative Commons Attribution Share Alike 2.0 Generic', 'href' => 'CC-BY-SA-2.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-2.0-UK' => [ 'id' => 'CC-BY-SA-2.0-UK', 'fullname' => 'Creative Commons Attribution Share Alike 2.0 England and Wales', 'href' => 'CC-BY-SA-2.0-UK.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-2.1-JP' => [ 'id' => 'CC-BY-SA-2.1-JP', 'fullname' => 'Creative Commons Attribution Share Alike 2.1 Japan', 'href' => 'CC-BY-SA-2.1-JP.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-2.5' => [ 'id' => 'CC-BY-SA-2.5', 'fullname' => 'Creative Commons Attribution Share Alike 2.5 Generic', 'href' => 'CC-BY-SA-2.5.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-3.0' => [ 'id' => 'CC-BY-SA-3.0', 'fullname' => 'Creative Commons Attribution Share Alike 3.0 Unported', 'href' => 'CC-BY-SA-3.0.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-3.0-AT' => [ 'id' => 'CC-BY-SA-3.0-AT', 'fullname' => 'Creative Commons Attribution Share Alike 3.0 Austria', 'href' => 'CC-BY-SA-3.0-AT.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-3.0-DE' => [ 'id' => 'CC-BY-SA-3.0-DE', 'fullname' => 'Creative Commons Attribution Share Alike 3.0 Germany', 'href' => 'CC-BY-SA-3.0-DE.html', 'free' => false, 'osi' => false ],
		'CC-BY-SA-4.0' => [ 'id' => 'CC-BY-SA-4.0', 'fullname' => 'Creative Commons Attribution Share Alike 4.0 International', 'href' => 'CC-BY-SA-4.0.html', 'free' => true, 'osi' => false ],
		'CC-PDDC' => [ 'id' => 'CC-PDDC', 'fullname' => 'Creative Commons Public Domain Dedication and Certification', 'href' => 'CC-PDDC.html', 'free' => false, 'osi' => false ],
		'CC0-1.0' => [ 'id' => 'CC0-1.0', 'fullname' => 'Creative Commons Zero v1.0 Universal', 'href' => 'CC0-1.0.html', 'free' => true, 'osi' => false ],
		'CDDL-1.0' => [ 'id' => 'CDDL-1.0', 'fullname' => 'Common Development and Distribution License 1.0', 'href' => 'CDDL-1.0.html', 'free' => true, 'osi' => true ],
		'CDDL-1.1' => [ 'id' => 'CDDL-1.1', 'fullname' => 'Common Development and Distribution License 1.1', 'href' => 'CDDL-1.1.html', 'free' => false, 'osi' => false ],
		'CDL-1.0' => [ 'id' => 'CDL-1.0', 'fullname' => 'Common Documentation License 1.0', 'href' => 'CDL-1.0.html', 'free' => false, 'osi' => false ],
		'CDLA-Permissive-1.0' => [ 'id' => 'CDLA-Permissive-1.0', 'fullname' => 'Community Data License Agreement Permissive 1.0', 'href' => 'CDLA-Permissive-1.0.html', 'free' => false, 'osi' => false ],
		'CDLA-Permissive-2.0' => [ 'id' => 'CDLA-Permissive-2.0', 'fullname' => 'Community Data License Agreement Permissive 2.0', 'href' => 'CDLA-Permissive-2.0.html', 'free' => false, 'osi' => false ],
		'CDLA-Sharing-1.0' => [ 'id' => 'CDLA-Sharing-1.0', 'fullname' => 'Community Data License Agreement Sharing 1.0', 'href' => 'CDLA-Sharing-1.0.html', 'free' => false, 'osi' => false ],
		'CECILL-1.0' => [ 'id' => 'CECILL-1.0', 'fullname' => 'CeCILL Free Software License Agreement v1.0', 'href' => 'CECILL-1.0.html', 'free' => false, 'osi' => false ],
		'CECILL-1.1' => [ 'id' => 'CECILL-1.1', 'fullname' => 'CeCILL Free Software License Agreement v1.1', 'href' => 'CECILL-1.1.html', 'free' => false, 'osi' => false ],
		'CECILL-2.0' => [ 'id' => 'CECILL-2.0', 'fullname' => 'CeCILL Free Software License Agreement v2.0', 'href' => 'CECILL-2.0.html', 'free' => true, 'osi' => false ],
		'CECILL-2.1' => [ 'id' => 'CECILL-2.1', 'fullname' => 'CeCILL Free Software License Agreement v2.1', 'href' => 'CECILL-2.1.html', 'free' => false, 'osi' => true ],
		'CECILL-B' => [ 'id' => 'CECILL-B', 'fullname' => 'CeCILL-B Free Software License Agreement', 'href' => 'CECILL-B.html', 'free' => true, 'osi' => false ],
		'CECILL-C' => [ 'id' => 'CECILL-C', 'fullname' => 'CeCILL-C Free Software License Agreement', 'href' => 'CECILL-C.html', 'free' => true, 'osi' => false ],
		'CERN-OHL-1.1' => [ 'id' => 'CERN-OHL-1.1', 'fullname' => 'CERN Open Hardware License v1.1', 'href' => 'CERN-OHL-1.1.html', 'free' => false, 'osi' => false ],
		'CERN-OHL-1.2' => [ 'id' => 'CERN-OHL-1.2', 'fullname' => 'CERN Open Hardware License v1.2', 'href' => 'CERN-OHL-1.2.html', 'free' => false, 'osi' => false ],
		'CERN-OHL-P-2.0' => [ 'id' => 'CERN-OHL-P-2.0', 'fullname' => 'CERN Open Hardware License Version 2 - Permissive', 'href' => 'CERN-OHL-P-2.0.html', 'free' => false, 'osi' => true ],
		'CERN-OHL-S-2.0' => [ 'id' => 'CERN-OHL-S-2.0', 'fullname' => 'CERN Open Hardware License Version 2 - Strongly Reciprocal', 'href' => 'CERN-OHL-S-2.0.html', 'free' => false, 'osi' => true ],
		'CERN-OHL-W-2.0' => [ 'id' => 'CERN-OHL-W-2.0', 'fullname' => 'CERN Open Hardware License Version 2 - Weakly Reciprocal', 'href' => 'CERN-OHL-W-2.0.html', 'free' => false, 'osi' => true ],
		'CFITSIO' => [ 'id' => 'CFITSIO', 'fullname' => 'CFITSIO License', 'href' => 'CFITSIO.html', 'free' => false, 'osi' => false ],
		'checkmk' => [ 'id' => 'checkmk', 'fullname' => 'Checkmk License', 'href' => 'checkmk.html', 'free' => false, 'osi' => false ],
		'ClArtistic' => [ 'id' => 'ClArtistic', 'fullname' => 'Clarified Artistic License', 'href' => 'ClArtistic.html', 'free' => true, 'osi' => false ],
		'Clips' => [ 'id' => 'Clips', 'fullname' => 'Clips License', 'href' => 'Clips.html', 'free' => false, 'osi' => false ],
		'CMU-Mach' => [ 'id' => 'CMU-Mach', 'fullname' => 'CMU Mach License', 'href' => 'CMU-Mach.html', 'free' => false, 'osi' => false ],
		'CNRI-Jython' => [ 'id' => 'CNRI-Jython', 'fullname' => 'CNRI Jython License', 'href' => 'CNRI-Jython.html', 'free' => false, 'osi' => false ],
		'CNRI-Python' => [ 'id' => 'CNRI-Python', 'fullname' => 'CNRI Python License', 'href' => 'CNRI-Python.html', 'free' => false, 'osi' => true ],
		'CNRI-Python-GPL-Compatible' => [ 'id' => 'CNRI-Python-GPL-Compatible', 'fullname' => 'CNRI Python Open Source GPL Compatible License Agreement', 'href' => 'CNRI-Python-GPL-Compatible.html', 'free' => false, 'osi' => false ],
		'COIL-1.0' => [ 'id' => 'COIL-1.0', 'fullname' => 'Copyfree Open Innovation License', 'href' => 'COIL-1.0.html', 'free' => false, 'osi' => false ],
		'Community-Spec-1.0' => [ 'id' => 'Community-Spec-1.0', 'fullname' => 'Community Specification License 1.0', 'href' => 'Community-Spec-1.0.html', 'free' => false, 'osi' => false ],
		'Condor-1.1' => [ 'id' => 'Condor-1.1', 'fullname' => 'Condor Public License v1.1', 'href' => 'Condor-1.1.html', 'free' => true, 'osi' => false ],
		'copyleft-next-0.3.0' => [ 'id' => 'copyleft-next-0.3.0', 'fullname' => 'copyleft-next 0.3.0', 'href' => 'copyleft-next-0.3.0.html', 'free' => false, 'osi' => false ],
		'copyleft-next-0.3.1' => [ 'id' => 'copyleft-next-0.3.1', 'fullname' => 'copyleft-next 0.3.1', 'href' => 'copyleft-next-0.3.1.html', 'free' => false, 'osi' => false ],
		'Cornell-Lossless-JPEG' => [ 'id' => 'Cornell-Lossless-JPEG', 'fullname' => 'Cornell Lossless JPEG License', 'href' => 'Cornell-Lossless-JPEG.html', 'free' => false, 'osi' => false ],
		'CPAL-1.0' => [ 'id' => 'CPAL-1.0', 'fullname' => 'Common Public Attribution License 1.0', 'href' => 'CPAL-1.0.html', 'free' => true, 'osi' => true ],
		'CPL-1.0' => [ 'id' => 'CPL-1.0', 'fullname' => 'Common Public License 1.0', 'href' => 'CPL-1.0.html', 'free' => true, 'osi' => true ],
		'CPOL-1.02' => [ 'id' => 'CPOL-1.02', 'fullname' => 'Code Project Open License 1.02', 'href' => 'CPOL-1.02.html', 'free' => false, 'osi' => false ],
		'Crossword' => [ 'id' => 'Crossword', 'fullname' => 'Crossword License', 'href' => 'Crossword.html', 'free' => false, 'osi' => false ],
		'CrystalStacker' => [ 'id' => 'CrystalStacker', 'fullname' => 'CrystalStacker License', 'href' => 'CrystalStacker.html', 'free' => false, 'osi' => false ],
		'CUA-OPL-1.0' => [ 'id' => 'CUA-OPL-1.0', 'fullname' => 'CUA Office Public License v1.0', 'href' => 'CUA-OPL-1.0.html', 'free' => false, 'osi' => true ],
		'Cube' => [ 'id' => 'Cube', 'fullname' => 'Cube License', 'href' => 'Cube.html', 'free' => false, 'osi' => false ],
		'curl' => [ 'id' => 'curl', 'fullname' => 'curl License', 'href' => 'curl.html', 'free' => false, 'osi' => false ],
		'D-FSL-1.0' => [ 'id' => 'D-FSL-1.0', 'fullname' => 'Deutsche Freie Software Lizenz', 'href' => 'D-FSL-1.0.html', 'free' => false, 'osi' => false ],
		'diffmark' => [ 'id' => 'diffmark', 'fullname' => 'diffmark license', 'href' => 'diffmark.html', 'free' => false, 'osi' => false ],
		'DL-DE-BY-2.0' => [ 'id' => 'DL-DE-BY-2.0', 'fullname' => 'Data license Germany – attribution – version 2.0', 'href' => 'DL-DE-BY-2.0.html', 'free' => false, 'osi' => false ],
		'DOC' => [ 'id' => 'DOC', 'fullname' => 'DOC License', 'href' => 'DOC.html', 'free' => false, 'osi' => false ],
		'Dotseqn' => [ 'id' => 'Dotseqn', 'fullname' => 'Dotseqn License', 'href' => 'Dotseqn.html', 'free' => false, 'osi' => false ],
		'DRL-1.0' => [ 'id' => 'DRL-1.0', 'fullname' => 'Detection Rule License 1.0', 'href' => 'DRL-1.0.html', 'free' => false, 'osi' => false ],
		'DSDP' => [ 'id' => 'DSDP', 'fullname' => 'DSDP License', 'href' => 'DSDP.html', 'free' => false, 'osi' => false ],
		'dvipdfm' => [ 'id' => 'dvipdfm', 'fullname' => 'dvipdfm License', 'href' => 'dvipdfm.html', 'free' => false, 'osi' => false ],
		'ECL-1.0' => [ 'id' => 'ECL-1.0', 'fullname' => 'Educational Community License v1.0', 'href' => 'ECL-1.0.html', 'free' => false, 'osi' => true ],
		'ECL-2.0' => [ 'id' => 'ECL-2.0', 'fullname' => 'Educational Community License v2.0', 'href' => 'ECL-2.0.html', 'free' => true, 'osi' => true ],
		'EFL-1.0' => [ 'id' => 'EFL-1.0', 'fullname' => 'Eiffel Forum License v1.0', 'href' => 'EFL-1.0.html', 'free' => false, 'osi' => true ],
		'EFL-2.0' => [ 'id' => 'EFL-2.0', 'fullname' => 'Eiffel Forum License v2.0', 'href' => 'EFL-2.0.html', 'free' => true, 'osi' => true ],
		'eGenix' => [ 'id' => 'eGenix', 'fullname' => 'eGenix.com Public License 1.1.0', 'href' => 'eGenix.html', 'free' => false, 'osi' => false ],
		'Elastic-2.0' => [ 'id' => 'Elastic-2.0', 'fullname' => 'Elastic License 2.0', 'href' => 'Elastic-2.0.html', 'free' => false, 'osi' => false ],
		'Entessa' => [ 'id' => 'Entessa', 'fullname' => 'Entessa Public License v1.0', 'href' => 'Entessa.html', 'free' => false, 'osi' => true ],
		'EPICS' => [ 'id' => 'EPICS', 'fullname' => 'EPICS Open License', 'href' => 'EPICS.html', 'free' => false, 'osi' => false ],
		'EPL-1.0' => [ 'id' => 'EPL-1.0', 'fullname' => 'Eclipse Public License 1.0', 'href' => 'EPL-1.0.html', 'free' => true, 'osi' => true ],
		'EPL-2.0' => [ 'id' => 'EPL-2.0', 'fullname' => 'Eclipse Public License 2.0', 'href' => 'EPL-2.0.html', 'free' => true, 'osi' => true ],
		'ErlPL-1.1' => [ 'id' => 'ErlPL-1.1', 'fullname' => 'Erlang Public License v1.1', 'href' => 'ErlPL-1.1.html', 'free' => false, 'osi' => false ],
		'etalab-2.0' => [ 'id' => 'etalab-2.0', 'fullname' => 'Etalab Open License 2.0', 'href' => 'etalab-2.0.html', 'free' => false, 'osi' => false ],
		'EUDatagrid' => [ 'id' => 'EUDatagrid', 'fullname' => 'EU DataGrid Software License', 'href' => 'EUDatagrid.html', 'free' => true, 'osi' => true ],
		'EUPL-1.0' => [ 'id' => 'EUPL-1.0', 'fullname' => 'European Union Public License 1.0', 'href' => 'EUPL-1.0.html', 'free' => false, 'osi' => false ],
		'EUPL-1.1' => [ 'id' => 'EUPL-1.1', 'fullname' => 'European Union Public License 1.1', 'href' => 'EUPL-1.1.html', 'free' => true, 'osi' => true ],
		'EUPL-1.2' => [ 'id' => 'EUPL-1.2', 'fullname' => 'European Union Public License 1.2', 'href' => 'EUPL-1.2.html', 'free' => true, 'osi' => true ],
		'Eurosym' => [ 'id' => 'Eurosym', 'fullname' => 'Eurosym License', 'href' => 'Eurosym.html', 'free' => false, 'osi' => false ],
		'Fair' => [ 'id' => 'Fair', 'fullname' => 'Fair License', 'href' => 'Fair.html', 'free' => false, 'osi' => true ],
		'FDK-AAC' => [ 'id' => 'FDK-AAC', 'fullname' => 'Fraunhofer FDK AAC Codec Library', 'href' => 'FDK-AAC.html', 'free' => false, 'osi' => false ],
		'Frameworx-1.0' => [ 'id' => 'Frameworx-1.0', 'fullname' => 'Frameworx Open License 1.0', 'href' => 'Frameworx-1.0.html', 'free' => false, 'osi' => true ],
		'FreeBSD-DOC' => [ 'id' => 'FreeBSD-DOC', 'fullname' => 'FreeBSD Documentation License', 'href' => 'FreeBSD-DOC.html', 'free' => false, 'osi' => false ],
		'FreeImage' => [ 'id' => 'FreeImage', 'fullname' => 'FreeImage Public License v1.0', 'href' => 'FreeImage.html', 'free' => false, 'osi' => false ],
		'FSFAP' => [ 'id' => 'FSFAP', 'fullname' => 'FSF All Permissive License', 'href' => 'FSFAP.html', 'free' => true, 'osi' => false ],
		'FSFUL' => [ 'id' => 'FSFUL', 'fullname' => 'FSF Unlimited License', 'href' => 'FSFUL.html', 'free' => false, 'osi' => false ],
		'FSFULLR' => [ 'id' => 'FSFULLR', 'fullname' => 'FSF Unlimited License (with License Retention)', 'href' => 'FSFULLR.html', 'free' => false, 'osi' => false ],
		'FSFULLRWD' => [ 'id' => 'FSFULLRWD', 'fullname' => 'FSF Unlimited License (With License Retention    and Warranty Disclaimer)', 'href' => 'FSFULLRWD.html', 'free' => false, 'osi' => false ],
		'FTL' => [ 'id' => 'FTL', 'fullname' => 'Freetype Project License', 'href' => 'FTL.html', 'free' => true, 'osi' => false ],
		'GD' => [ 'id' => 'GD', 'fullname' => 'GD License', 'href' => 'GD.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1-invariants-only' => [ 'id' => 'GFDL-1.1-invariants-only', 'fullname' => 'GNU Free Documentation License v1.1 only - invariants', 'href' => 'GFDL-1.1-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1-invariants-or-later' => [ 'id' => 'GFDL-1.1-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.1 or later - invariants', 'href' => 'GFDL-1.1-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1-no-invariants-only' => [ 'id' => 'GFDL-1.1-no-invariants-only', 'fullname' => 'GNU Free Documentation License v1.1 only - no invariants', 'href' => 'GFDL-1.1-no-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1-no-invariants-or-later' => [ 'id' => 'GFDL-1.1-no-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.1 or later - no invariants', 'href' => 'GFDL-1.1-no-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1-only' => [ 'id' => 'GFDL-1.1-only', 'fullname' => 'GNU Free Documentation License v1.1 only', 'href' => 'GFDL-1.1-only.html', 'free' => true, 'osi' => false ],
		'GFDL-1.1-or-later' => [ 'id' => 'GFDL-1.1-or-later', 'fullname' => 'GNU Free Documentation License v1.1 or later', 'href' => 'GFDL-1.1-or-later.html', 'free' => true, 'osi' => false ],
		'GFDL-1.2-invariants-only' => [ 'id' => 'GFDL-1.2-invariants-only', 'fullname' => 'GNU Free Documentation License v1.2 only - invariants', 'href' => 'GFDL-1.2-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.2-invariants-or-later' => [ 'id' => 'GFDL-1.2-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.2 or later - invariants', 'href' => 'GFDL-1.2-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.2-no-invariants-only' => [ 'id' => 'GFDL-1.2-no-invariants-only', 'fullname' => 'GNU Free Documentation License v1.2 only - no invariants', 'href' => 'GFDL-1.2-no-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.2-no-invariants-or-later' => [ 'id' => 'GFDL-1.2-no-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.2 or later - no invariants', 'href' => 'GFDL-1.2-no-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.2-only' => [ 'id' => 'GFDL-1.2-only', 'fullname' => 'GNU Free Documentation License v1.2 only', 'href' => 'GFDL-1.2-only.html', 'free' => true, 'osi' => false ],
		'GFDL-1.2-or-later' => [ 'id' => 'GFDL-1.2-or-later', 'fullname' => 'GNU Free Documentation License v1.2 or later', 'href' => 'GFDL-1.2-or-later.html', 'free' => true, 'osi' => false ],
		'GFDL-1.3-invariants-only' => [ 'id' => 'GFDL-1.3-invariants-only', 'fullname' => 'GNU Free Documentation License v1.3 only - invariants', 'href' => 'GFDL-1.3-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.3-invariants-or-later' => [ 'id' => 'GFDL-1.3-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.3 or later - invariants', 'href' => 'GFDL-1.3-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.3-no-invariants-only' => [ 'id' => 'GFDL-1.3-no-invariants-only', 'fullname' => 'GNU Free Documentation License v1.3 only - no invariants', 'href' => 'GFDL-1.3-no-invariants-only.html', 'free' => false, 'osi' => false ],
		'GFDL-1.3-no-invariants-or-later' => [ 'id' => 'GFDL-1.3-no-invariants-or-later', 'fullname' => 'GNU Free Documentation License v1.3 or later - no invariants', 'href' => 'GFDL-1.3-no-invariants-or-later.html', 'free' => false, 'osi' => false ],
		'GFDL-1.3-only' => [ 'id' => 'GFDL-1.3-only', 'fullname' => 'GNU Free Documentation License v1.3 only', 'href' => 'GFDL-1.3-only.html', 'free' => true, 'osi' => false ],
		'GFDL-1.3-or-later' => [ 'id' => 'GFDL-1.3-or-later', 'fullname' => 'GNU Free Documentation License v1.3 or later', 'href' => 'GFDL-1.3-or-later.html', 'free' => true, 'osi' => false ],
		'Giftware' => [ 'id' => 'Giftware', 'fullname' => 'Giftware License', 'href' => 'Giftware.html', 'free' => false, 'osi' => false ],
		'GL2PS' => [ 'id' => 'GL2PS', 'fullname' => 'GL2PS License', 'href' => 'GL2PS.html', 'free' => false, 'osi' => false ],
		'Glide' => [ 'id' => 'Glide', 'fullname' => '3dfx Glide License', 'href' => 'Glide.html', 'free' => false, 'osi' => false ],
		'Glulxe' => [ 'id' => 'Glulxe', 'fullname' => 'Glulxe License', 'href' => 'Glulxe.html', 'free' => false, 'osi' => false ],
		'GLWTPL' => [ 'id' => 'GLWTPL', 'fullname' => 'Good Luck With That Public License', 'href' => 'GLWTPL.html', 'free' => false, 'osi' => false ],
		'gnuplot' => [ 'id' => 'gnuplot', 'fullname' => 'gnuplot License', 'href' => 'gnuplot.html', 'free' => true, 'osi' => false ],
		'GPL-1.0-only' => [ 'id' => 'GPL-1.0-only', 'fullname' => 'GNU General Public License v1.0 only', 'href' => 'GPL-1.0-only.html', 'free' => false, 'osi' => false ],
		'GPL-1.0-or-later' => [ 'id' => 'GPL-1.0-or-later', 'fullname' => 'GNU General Public License v1.0 or later', 'href' => 'GPL-1.0-or-later.html', 'free' => false, 'osi' => false ],
		'GPL-2.0-only' => [ 'id' => 'GPL-2.0-only', 'fullname' => 'GNU General Public License v2.0 only', 'href' => 'GPL-2.0-only.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-or-later' => [ 'id' => 'GPL-2.0-or-later', 'fullname' => 'GNU General Public License v2.0 or later', 'href' => 'GPL-2.0-or-later.html', 'free' => true, 'osi' => true ],
		'GPL-3.0-only' => [ 'id' => 'GPL-3.0-only', 'fullname' => 'GNU General Public License v3.0 only', 'href' => 'GPL-3.0-only.html', 'free' => true, 'osi' => true ],
		'GPL-3.0-or-later' => [ 'id' => 'GPL-3.0-or-later', 'fullname' => 'GNU General Public License v3.0 or later', 'href' => 'GPL-3.0-or-later.html', 'free' => true, 'osi' => true ],
		'Graphics-Gems' => [ 'id' => 'Graphics-Gems', 'fullname' => 'Graphics Gems License', 'href' => 'Graphics-Gems.html', 'free' => false, 'osi' => false ],
		'gSOAP-1.3b' => [ 'id' => 'gSOAP-1.3b', 'fullname' => 'gSOAP Public License v1.3b', 'href' => 'gSOAP-1.3b.html', 'free' => false, 'osi' => false ],
		'HaskellReport' => [ 'id' => 'HaskellReport', 'fullname' => 'Haskell Language Report License', 'href' => 'HaskellReport.html', 'free' => false, 'osi' => false ],
		'Hippocratic-2.1' => [ 'id' => 'Hippocratic-2.1', 'fullname' => 'Hippocratic License 2.1', 'href' => 'Hippocratic-2.1.html', 'free' => false, 'osi' => false ],
		'HP-1986' => [ 'id' => 'HP-1986', 'fullname' => 'Hewlett-Packard 1986 License', 'href' => 'HP-1986.html', 'free' => false, 'osi' => false ],
		'HPND' => [ 'id' => 'HPND', 'fullname' => 'Historical Permission Notice and Disclaimer', 'href' => 'HPND.html', 'free' => true, 'osi' => true ],
		'HPND-export-US' => [ 'id' => 'HPND-export-US', 'fullname' => 'HPND with US Government export control warning', 'href' => 'HPND-export-US.html', 'free' => false, 'osi' => false ],
		'HPND-Markus-Kuhn' => [ 'id' => 'HPND-Markus-Kuhn', 'fullname' => 'Historical Permission Notice and Disclaimer - Markus Kuhn variant', 'href' => 'HPND-Markus-Kuhn.html', 'free' => false, 'osi' => false ],
		'HPND-sell-variant' => [ 'id' => 'HPND-sell-variant', 'fullname' => 'Historical Permission Notice and Disclaimer - sell variant', 'href' => 'HPND-sell-variant.html', 'free' => false, 'osi' => false ],
		'HPND-sell-variant-MIT-disclaimer' => [ 'id' => 'HPND-sell-variant-MIT-disclaimer', 'fullname' => 'HPND sell variant with MIT disclaimer', 'href' => 'HPND-sell-variant-MIT-disclaimer.html', 'free' => false, 'osi' => false ],
		'HTMLTIDY' => [ 'id' => 'HTMLTIDY', 'fullname' => 'HTML Tidy License', 'href' => 'HTMLTIDY.html', 'free' => false, 'osi' => false ],
		'IBM-pibs' => [ 'id' => 'IBM-pibs', 'fullname' => 'IBM PowerPC Initialization and Boot Software', 'href' => 'IBM-pibs.html', 'free' => false, 'osi' => false ],
		'ICU' => [ 'id' => 'ICU', 'fullname' => 'ICU License', 'href' => 'ICU.html', 'free' => false, 'osi' => false ],
		'IEC-Code-Components-EULA' => [ 'id' => 'IEC-Code-Components-EULA', 'fullname' => 'IEC    Code Components End-user license agreement', 'href' => 'IEC-Code-Components-EULA.html', 'free' => false, 'osi' => false ],
		'IJG' => [ 'id' => 'IJG', 'fullname' => 'Independent JPEG Group License', 'href' => 'IJG.html', 'free' => true, 'osi' => false ],
		'IJG-short' => [ 'id' => 'IJG-short', 'fullname' => 'Independent JPEG Group License - short', 'href' => 'IJG-short.html', 'free' => false, 'osi' => false ],
		'ImageMagick' => [ 'id' => 'ImageMagick', 'fullname' => 'ImageMagick License', 'href' => 'ImageMagick.html', 'free' => false, 'osi' => false ],
		'iMatix' => [ 'id' => 'iMatix', 'fullname' => 'iMatix Standard Function Library Agreement', 'href' => 'iMatix.html', 'free' => true, 'osi' => false ],
		'Imlib2' => [ 'id' => 'Imlib2', 'fullname' => 'Imlib2 License', 'href' => 'Imlib2.html', 'free' => true, 'osi' => false ],
		'Info-ZIP' => [ 'id' => 'Info-ZIP', 'fullname' => 'Info-ZIP License', 'href' => 'Info-ZIP.html', 'free' => false, 'osi' => false ],
		'Intel' => [ 'id' => 'Intel', 'fullname' => 'Intel Open Source License', 'href' => 'Intel.html', 'free' => true, 'osi' => true ],
		'Intel-ACPI' => [ 'id' => 'Intel-ACPI', 'fullname' => 'Intel ACPI Software License Agreement', 'href' => 'Intel-ACPI.html', 'free' => false, 'osi' => false ],
		'Interbase-1.0' => [ 'id' => 'Interbase-1.0', 'fullname' => 'Interbase Public License v1.0', 'href' => 'Interbase-1.0.html', 'free' => false, 'osi' => false ],
		'IPA' => [ 'id' => 'IPA', 'fullname' => 'IPA Font License', 'href' => 'IPA.html', 'free' => true, 'osi' => true ],
		'IPL-1.0' => [ 'id' => 'IPL-1.0', 'fullname' => 'IBM Public License v1.0', 'href' => 'IPL-1.0.html', 'free' => true, 'osi' => true ],
		'ISC' => [ 'id' => 'ISC', 'fullname' => 'ISC License', 'href' => 'ISC.html', 'free' => true, 'osi' => true ],
		'Jam' => [ 'id' => 'Jam', 'fullname' => 'Jam License', 'href' => 'Jam.html', 'free' => false, 'osi' => true ],
		'JasPer-2.0' => [ 'id' => 'JasPer-2.0', 'fullname' => 'JasPer License', 'href' => 'JasPer-2.0.html', 'free' => false, 'osi' => false ],
		'JPL-image' => [ 'id' => 'JPL-image', 'fullname' => 'JPL Image Use Policy', 'href' => 'JPL-image.html', 'free' => false, 'osi' => false ],
		'JPNIC' => [ 'id' => 'JPNIC', 'fullname' => 'Japan Network Information Center License', 'href' => 'JPNIC.html', 'free' => false, 'osi' => false ],
		'JSON' => [ 'id' => 'JSON', 'fullname' => 'JSON License', 'href' => 'JSON.html', 'free' => false, 'osi' => false ],
		'Kazlib' => [ 'id' => 'Kazlib', 'fullname' => 'Kazlib License', 'href' => 'Kazlib.html', 'free' => false, 'osi' => false ],
		'Knuth-CTAN' => [ 'id' => 'Knuth-CTAN', 'fullname' => 'Knuth CTAN License', 'href' => 'Knuth-CTAN.html', 'free' => false, 'osi' => false ],
		'LAL-1.2' => [ 'id' => 'LAL-1.2', 'fullname' => 'License Art Libre 1.2', 'href' => 'LAL-1.2.html', 'free' => false, 'osi' => false ],
		'LAL-1.3' => [ 'id' => 'LAL-1.3', 'fullname' => 'License Art Libre 1.3', 'href' => 'LAL-1.3.html', 'free' => false, 'osi' => false ],
		'Latex2e' => [ 'id' => 'Latex2e', 'fullname' => 'Latex2e License', 'href' => 'Latex2e.html', 'free' => false, 'osi' => false ],
		'Leptonica' => [ 'id' => 'Leptonica', 'fullname' => 'Leptonica License', 'href' => 'Leptonica.html', 'free' => false, 'osi' => false ],
		'LGPL-2.0-only' => [ 'id' => 'LGPL-2.0-only', 'fullname' => 'GNU Library General Public License v2 only', 'href' => 'LGPL-2.0-only.html', 'free' => false, 'osi' => true ],
		'LGPL-2.0-or-later' => [ 'id' => 'LGPL-2.0-or-later', 'fullname' => 'GNU Library General Public License v2 or later', 'href' => 'LGPL-2.0-or-later.html', 'free' => false, 'osi' => true ],
		'LGPL-2.1-only' => [ 'id' => 'LGPL-2.1-only', 'fullname' => 'GNU Lesser General Public License v2.1 only', 'href' => 'LGPL-2.1-only.html', 'free' => true, 'osi' => true ],
		'LGPL-2.1-or-later' => [ 'id' => 'LGPL-2.1-or-later', 'fullname' => 'GNU Lesser General Public License v2.1 or later', 'href' => 'LGPL-2.1-or-later.html', 'free' => true, 'osi' => true ],
		'LGPL-3.0-only' => [ 'id' => 'LGPL-3.0-only', 'fullname' => 'GNU Lesser General Public License v3.0 only', 'href' => 'LGPL-3.0-only.html', 'free' => true, 'osi' => true ],
		'LGPL-3.0-or-later' => [ 'id' => 'LGPL-3.0-or-later', 'fullname' => 'GNU Lesser General Public License v3.0 or later', 'href' => 'LGPL-3.0-or-later.html', 'free' => true, 'osi' => true ],
		'LGPLLR' => [ 'id' => 'LGPLLR', 'fullname' => 'Lesser General Public License For Linguistic Resources', 'href' => 'LGPLLR.html', 'free' => false, 'osi' => false ],
		'Libpng' => [ 'id' => 'Libpng', 'fullname' => 'libpng License', 'href' => 'Libpng.html', 'free' => false, 'osi' => false ],
		'libpng-2.0' => [ 'id' => 'libpng-2.0', 'fullname' => 'PNG Reference Library version 2', 'href' => 'libpng-2.0.html', 'free' => false, 'osi' => false ],
		'libselinux-1.0' => [ 'id' => 'libselinux-1.0', 'fullname' => 'libselinux public domain notice', 'href' => 'libselinux-1.0.html', 'free' => false, 'osi' => false ],
		'libtiff' => [ 'id' => 'libtiff', 'fullname' => 'libtiff License', 'href' => 'libtiff.html', 'free' => false, 'osi' => false ],
		'libutil-David-Nugent' => [ 'id' => 'libutil-David-Nugent', 'fullname' => 'libutil David Nugent License', 'href' => 'libutil-David-Nugent.html', 'free' => false, 'osi' => false ],
		'LiLiQ-P-1.1' => [ 'id' => 'LiLiQ-P-1.1', 'fullname' => 'License Libre du Québec – Permissive version 1.1', 'href' => 'LiLiQ-P-1.1.html', 'free' => false, 'osi' => true ],
		'LiLiQ-R-1.1' => [ 'id' => 'LiLiQ-R-1.1', 'fullname' => 'License Libre du Québec – Réciprocité version 1.1', 'href' => 'LiLiQ-R-1.1.html', 'free' => false, 'osi' => true ],
		'LiLiQ-Rplus-1.1' => [ 'id' => 'LiLiQ-Rplus-1.1', 'fullname' => 'License Libre du Québec – Réciprocité forte version 1.1', 'href' => 'LiLiQ-Rplus-1.1.html', 'free' => false, 'osi' => true ],
		'Linux-man-pages-copyleft' => [ 'id' => 'Linux-man-pages-copyleft', 'fullname' => 'Linux man-pages Copyleft', 'href' => 'Linux-man-pages-copyleft.html', 'free' => false, 'osi' => false ],
		'Linux-OpenIB' => [ 'id' => 'Linux-OpenIB', 'fullname' => 'Linux Kernel Variant of OpenIB.org license', 'href' => 'Linux-OpenIB.html', 'free' => false, 'osi' => false ],
		'LOOP' => [ 'id' => 'LOOP', 'fullname' => 'Common Lisp LOOP License', 'href' => 'LOOP.html', 'free' => false, 'osi' => false ],
		'LPL-1.0' => [ 'id' => 'LPL-1.0', 'fullname' => 'Lucent Public License Version 1.0', 'href' => 'LPL-1.0.html', 'free' => false, 'osi' => true ],
		'LPL-1.02' => [ 'id' => 'LPL-1.02', 'fullname' => 'Lucent Public License v1.02', 'href' => 'LPL-1.02.html', 'free' => true, 'osi' => true ],
		'LPPL-1.0' => [ 'id' => 'LPPL-1.0', 'fullname' => 'LaTeX Project Public License v1.0', 'href' => 'LPPL-1.0.html', 'free' => false, 'osi' => false ],
		'LPPL-1.1' => [ 'id' => 'LPPL-1.1', 'fullname' => 'LaTeX Project Public License v1.1', 'href' => 'LPPL-1.1.html', 'free' => false, 'osi' => false ],
		'LPPL-1.2' => [ 'id' => 'LPPL-1.2', 'fullname' => 'LaTeX Project Public License v1.2', 'href' => 'LPPL-1.2.html', 'free' => true, 'osi' => false ],
		'LPPL-1.3a' => [ 'id' => 'LPPL-1.3a', 'fullname' => 'LaTeX Project Public License v1.3a', 'href' => 'LPPL-1.3a.html', 'free' => true, 'osi' => false ],
		'LPPL-1.3c' => [ 'id' => 'LPPL-1.3c', 'fullname' => 'LaTeX Project Public License v1.3c', 'href' => 'LPPL-1.3c.html', 'free' => false, 'osi' => true ],
		'LZMA-SDK-9.11-to-9.20' => [ 'id' => 'LZMA-SDK-9.11-to-9.20', 'fullname' => 'LZMA SDK License (versions 9.11 to 9.20)', 'href' => 'LZMA-SDK-9.11-to-9.20.html', 'free' => false, 'osi' => false ],
		'LZMA-SDK-9.22' => [ 'id' => 'LZMA-SDK-9.22', 'fullname' => 'LZMA SDK License (versions 9.22 and beyond)', 'href' => 'LZMA-SDK-9.22.html', 'free' => false, 'osi' => false ],
		'MakeIndex' => [ 'id' => 'MakeIndex', 'fullname' => 'MakeIndex License', 'href' => 'MakeIndex.html', 'free' => false, 'osi' => false ],
		'Martin-Birgmeier' => [ 'id' => 'Martin-Birgmeier', 'fullname' => 'Martin Birgmeier License', 'href' => 'Martin-Birgmeier.html', 'free' => false, 'osi' => false ],
		'Minpack' => [ 'id' => 'Minpack', 'fullname' => 'Minpack License', 'href' => 'Minpack.html', 'free' => false, 'osi' => false ],
		'MirOS' => [ 'id' => 'MirOS', 'fullname' => 'The MirOS License', 'href' => 'MirOS.html', 'free' => false, 'osi' => true ],
		'MIT' => [ 'id' => 'MIT', 'fullname' => 'MIT License', 'href' => 'MIT.html', 'free' => true, 'osi' => true ],
		'MIT-0' => [ 'id' => 'MIT-0', 'fullname' => 'MIT No Attribution', 'href' => 'MIT-0.html', 'free' => false, 'osi' => true ],
		'MIT-advertising' => [ 'id' => 'MIT-advertising', 'fullname' => 'Enlightenment License (e16)', 'href' => 'MIT-advertising.html', 'free' => false, 'osi' => false ],
		'MIT-CMU' => [ 'id' => 'MIT-CMU', 'fullname' => 'CMU License', 'href' => 'MIT-CMU.html', 'free' => false, 'osi' => false ],
		'MIT-enna' => [ 'id' => 'MIT-enna', 'fullname' => 'enna License', 'href' => 'MIT-enna.html', 'free' => false, 'osi' => false ],
		'MIT-feh' => [ 'id' => 'MIT-feh', 'fullname' => 'feh License', 'href' => 'MIT-feh.html', 'free' => false, 'osi' => false ],
		'MIT-Modern-Variant' => [ 'id' => 'MIT-Modern-Variant', 'fullname' => 'MIT License Modern Variant', 'href' => 'MIT-Modern-Variant.html', 'free' => false, 'osi' => true ],
		'MIT-open-group' => [ 'id' => 'MIT-open-group', 'fullname' => 'MIT Open Group variant', 'href' => 'MIT-open-group.html', 'free' => false, 'osi' => false ],
		'MIT-Wu' => [ 'id' => 'MIT-Wu', 'fullname' => 'MIT Tom Wu Variant', 'href' => 'MIT-Wu.html', 'free' => false, 'osi' => false ],
		'MITNFA' => [ 'id' => 'MITNFA', 'fullname' => 'MIT +no-false-attribs license', 'href' => 'MITNFA.html', 'free' => false, 'osi' => false ],
		'Motosoto' => [ 'id' => 'Motosoto', 'fullname' => 'Motosoto License', 'href' => 'Motosoto.html', 'free' => false, 'osi' => true ],
		'mpi-permissive' => [ 'id' => 'mpi-permissive', 'fullname' => 'mpi Permissive License', 'href' => 'mpi-permissive.html', 'free' => false, 'osi' => false ],
		'mpich2' => [ 'id' => 'mpich2', 'fullname' => 'mpich2 License', 'href' => 'mpich2.html', 'free' => false, 'osi' => false ],
		'MPL-1.0' => [ 'id' => 'MPL-1.0', 'fullname' => 'Mozilla Public License 1.0', 'href' => 'MPL-1.0.html', 'free' => false, 'osi' => true ],
		'MPL-1.1' => [ 'id' => 'MPL-1.1', 'fullname' => 'Mozilla Public License 1.1', 'href' => 'MPL-1.1.html', 'free' => true, 'osi' => true ],
		'MPL-2.0' => [ 'id' => 'MPL-2.0', 'fullname' => 'Mozilla Public License 2.0', 'href' => 'MPL-2.0.html', 'free' => true, 'osi' => true ],
		'MPL-2.0-no-copyleft-exception' => [ 'id' => 'MPL-2.0-no-copyleft-exception', 'fullname' => 'Mozilla Public License 2.0 (no copyleft exception)', 'href' => 'MPL-2.0-no-copyleft-exception.html', 'free' => false, 'osi' => true ],
		'mplus' => [ 'id' => 'mplus', 'fullname' => 'mplus Font License', 'href' => 'mplus.html', 'free' => false, 'osi' => false ],
		'MS-LPL' => [ 'id' => 'MS-LPL', 'fullname' => 'Microsoft Limited Public License', 'href' => 'MS-LPL.html', 'free' => false, 'osi' => false ],
		'MS-PL' => [ 'id' => 'MS-PL', 'fullname' => 'Microsoft Public License', 'href' => 'MS-PL.html', 'free' => true, 'osi' => true ],
		'MS-RL' => [ 'id' => 'MS-RL', 'fullname' => 'Microsoft Reciprocal License', 'href' => 'MS-RL.html', 'free' => true, 'osi' => true ],
		'MTLL' => [ 'id' => 'MTLL', 'fullname' => 'Matrix Template Library License', 'href' => 'MTLL.html', 'free' => false, 'osi' => false ],
		'MulanPSL-1.0' => [ 'id' => 'MulanPSL-1.0', 'fullname' => 'Mulan Permissive Software License, Version 1', 'href' => 'MulanPSL-1.0.html', 'free' => false, 'osi' => false ],
		'MulanPSL-2.0' => [ 'id' => 'MulanPSL-2.0', 'fullname' => 'Mulan Permissive Software License, Version 2', 'href' => 'MulanPSL-2.0.html', 'free' => false, 'osi' => true ],
		'Multics' => [ 'id' => 'Multics', 'fullname' => 'Multics License', 'href' => 'Multics.html', 'free' => false, 'osi' => true ],
		'Mup' => [ 'id' => 'Mup', 'fullname' => 'Mup License', 'href' => 'Mup.html', 'free' => false, 'osi' => false ],
		'NAIST-2003' => [ 'id' => 'NAIST-2003', 'fullname' => 'Nara Institute of Science and Technology License (2003)', 'href' => 'NAIST-2003.html', 'free' => false, 'osi' => false ],
		'NASA-1.3' => [ 'id' => 'NASA-1.3', 'fullname' => 'NASA Open Source Agreement 1.3', 'href' => 'NASA-1.3.html', 'free' => false, 'osi' => true ],
		'Naumen' => [ 'id' => 'Naumen', 'fullname' => 'Naumen Public License', 'href' => 'Naumen.html', 'free' => false, 'osi' => true ],
		'NBPL-1.0' => [ 'id' => 'NBPL-1.0', 'fullname' => 'Net Boolean Public License v1', 'href' => 'NBPL-1.0.html', 'free' => false, 'osi' => false ],
		'NCGL-UK-2.0' => [ 'id' => 'NCGL-UK-2.0', 'fullname' => 'Non-Commercial Government License', 'href' => 'NCGL-UK-2.0.html', 'free' => false, 'osi' => false ],
		'NCSA' => [ 'id' => 'NCSA', 'fullname' => 'University of Illinois/NCSA Open Source License', 'href' => 'NCSA.html', 'free' => true, 'osi' => true ],
		'Net-SNMP' => [ 'id' => 'Net-SNMP', 'fullname' => 'Net-SNMP License', 'href' => 'Net-SNMP.html', 'free' => false, 'osi' => false ],
		'NetCDF' => [ 'id' => 'NetCDF', 'fullname' => 'NetCDF license', 'href' => 'NetCDF.html', 'free' => false, 'osi' => false ],
		'Newsletr' => [ 'id' => 'Newsletr', 'fullname' => 'Newsletr License', 'href' => 'Newsletr.html', 'free' => false, 'osi' => false ],
		'NGPL' => [ 'id' => 'NGPL', 'fullname' => 'Nethack General Public License', 'href' => 'NGPL.html', 'free' => false, 'osi' => true ],
		'NICTA-1.0' => [ 'id' => 'NICTA-1.0', 'fullname' => 'NICTA Public Software License, Version 1.0', 'href' => 'NICTA-1.0.html', 'free' => false, 'osi' => false ],
		'NIST-PD' => [ 'id' => 'NIST-PD', 'fullname' => 'NIST Public Domain Notice', 'href' => 'NIST-PD.html', 'free' => false, 'osi' => false ],
		'NIST-PD-fallback' => [ 'id' => 'NIST-PD-fallback', 'fullname' => 'NIST Public Domain Notice with license fallback', 'href' => 'NIST-PD-fallback.html', 'free' => false, 'osi' => false ],
		'NLOD-1.0' => [ 'id' => 'NLOD-1.0', 'fullname' => 'Norwegian License for Open Government Data (NLOD) 1.0', 'href' => 'NLOD-1.0.html', 'free' => false, 'osi' => false ],
		'NLOD-2.0' => [ 'id' => 'NLOD-2.0', 'fullname' => 'Norwegian License for Open Government Data (NLOD) 2.0', 'href' => 'NLOD-2.0.html', 'free' => false, 'osi' => false ],
		'NLPL' => [ 'id' => 'NLPL', 'fullname' => 'No Limit Public License', 'href' => 'NLPL.html', 'free' => false, 'osi' => false ],
		'Nokia' => [ 'id' => 'Nokia', 'fullname' => 'Nokia Open Source License', 'href' => 'Nokia.html', 'free' => true, 'osi' => true ],
		'NOSL' => [ 'id' => 'NOSL', 'fullname' => 'Netizen Open Source License', 'href' => 'NOSL.html', 'free' => true, 'osi' => false ],
		'Noweb' => [ 'id' => 'Noweb', 'fullname' => 'Noweb License', 'href' => 'Noweb.html', 'free' => false, 'osi' => false ],
		'NPL-1.0' => [ 'id' => 'NPL-1.0', 'fullname' => 'Netscape Public License v1.0', 'href' => 'NPL-1.0.html', 'free' => true, 'osi' => false ],
		'NPL-1.1' => [ 'id' => 'NPL-1.1', 'fullname' => 'Netscape Public License v1.1', 'href' => 'NPL-1.1.html', 'free' => true, 'osi' => false ],
		'NPOSL-3.0' => [ 'id' => 'NPOSL-3.0', 'fullname' => 'Non-Profit Open Software License 3.0', 'href' => 'NPOSL-3.0.html', 'free' => false, 'osi' => true ],
		'NRL' => [ 'id' => 'NRL', 'fullname' => 'NRL License', 'href' => 'NRL.html', 'free' => false, 'osi' => false ],
		'NTP' => [ 'id' => 'NTP', 'fullname' => 'NTP License', 'href' => 'NTP.html', 'free' => false, 'osi' => true ],
		'NTP-0' => [ 'id' => 'NTP-0', 'fullname' => 'NTP No Attribution', 'href' => 'NTP-0.html', 'free' => false, 'osi' => false ],
		'O-UDA-1.0' => [ 'id' => 'O-UDA-1.0', 'fullname' => 'Open Use of Data Agreement v1.0', 'href' => 'O-UDA-1.0.html', 'free' => false, 'osi' => false ],
		'OCCT-PL' => [ 'id' => 'OCCT-PL', 'fullname' => 'Open CASCADE Technology Public License', 'href' => 'OCCT-PL.html', 'free' => false, 'osi' => false ],
		'OCLC-2.0' => [ 'id' => 'OCLC-2.0', 'fullname' => 'OCLC Research Public License 2.0', 'href' => 'OCLC-2.0.html', 'free' => false, 'osi' => true ],
		'ODbL-1.0' => [ 'id' => 'ODbL-1.0', 'fullname' => 'Open Data Commons Open Database License v1.0', 'href' => 'ODbL-1.0.html', 'free' => true, 'osi' => false ],
		'ODC-By-1.0' => [ 'id' => 'ODC-By-1.0', 'fullname' => 'Open Data Commons Attribution License v1.0', 'href' => 'ODC-By-1.0.html', 'free' => false, 'osi' => false ],
		'OFFIS' => [ 'id' => 'OFFIS', 'fullname' => 'OFFIS License', 'href' => 'OFFIS.html', 'free' => false, 'osi' => false ],
		'OFL-1.0' => [ 'id' => 'OFL-1.0', 'fullname' => 'SIL Open Font License 1.0', 'href' => 'OFL-1.0.html', 'free' => true, 'osi' => false ],
		'OFL-1.0-no-RFN' => [ 'id' => 'OFL-1.0-no-RFN', 'fullname' => 'SIL Open Font License 1.0 with no Reserved Font Name', 'href' => 'OFL-1.0-no-RFN.html', 'free' => false, 'osi' => false ],
		'OFL-1.0-RFN' => [ 'id' => 'OFL-1.0-RFN', 'fullname' => 'SIL Open Font License 1.0 with Reserved Font Name', 'href' => 'OFL-1.0-RFN.html', 'free' => false, 'osi' => false ],
		'OFL-1.1' => [ 'id' => 'OFL-1.1', 'fullname' => 'SIL Open Font License 1.1', 'href' => 'OFL-1.1.html', 'free' => true, 'osi' => true ],
		'OFL-1.1-no-RFN' => [ 'id' => 'OFL-1.1-no-RFN', 'fullname' => 'SIL Open Font License 1.1 with no Reserved Font Name', 'href' => 'OFL-1.1-no-RFN.html', 'free' => false, 'osi' => true ],
		'OFL-1.1-RFN' => [ 'id' => 'OFL-1.1-RFN', 'fullname' => 'SIL Open Font License 1.1 with Reserved Font Name', 'href' => 'OFL-1.1-RFN.html', 'free' => false, 'osi' => true ],
		'OGC-1.0' => [ 'id' => 'OGC-1.0', 'fullname' => 'OGC Software License, Version 1.0', 'href' => 'OGC-1.0.html', 'free' => false, 'osi' => false ],
		'OGDL-Taiwan-1.0' => [ 'id' => 'OGDL-Taiwan-1.0', 'fullname' => 'Taiwan Open Government Data License, version 1.0', 'href' => 'OGDL-Taiwan-1.0.html', 'free' => false, 'osi' => false ],
		'OGL-Canada-2.0' => [ 'id' => 'OGL-Canada-2.0', 'fullname' => 'Open Government License - Canada', 'href' => 'OGL-Canada-2.0.html', 'free' => false, 'osi' => false ],
		'OGL-UK-1.0' => [ 'id' => 'OGL-UK-1.0', 'fullname' => 'Open Government License v1.0', 'href' => 'OGL-UK-1.0.html', 'free' => false, 'osi' => false ],
		'OGL-UK-2.0' => [ 'id' => 'OGL-UK-2.0', 'fullname' => 'Open Government License v2.0', 'href' => 'OGL-UK-2.0.html', 'free' => false, 'osi' => false ],
		'OGL-UK-3.0' => [ 'id' => 'OGL-UK-3.0', 'fullname' => 'Open Government License v3.0', 'href' => 'OGL-UK-3.0.html', 'free' => false, 'osi' => false ],
		'OGTSL' => [ 'id' => 'OGTSL', 'fullname' => 'Open Group Test Suite License', 'href' => 'OGTSL.html', 'free' => false, 'osi' => true ],
		'OLDAP-1.1' => [ 'id' => 'OLDAP-1.1', 'fullname' => 'Open LDAP Public License v1.1', 'href' => 'OLDAP-1.1.html', 'free' => false, 'osi' => false ],
		'OLDAP-1.2' => [ 'id' => 'OLDAP-1.2', 'fullname' => 'Open LDAP Public License v1.2', 'href' => 'OLDAP-1.2.html', 'free' => false, 'osi' => false ],
		'OLDAP-1.3' => [ 'id' => 'OLDAP-1.3', 'fullname' => 'Open LDAP Public License v1.3', 'href' => 'OLDAP-1.3.html', 'free' => false, 'osi' => false ],
		'OLDAP-1.4' => [ 'id' => 'OLDAP-1.4', 'fullname' => 'Open LDAP Public License v1.4', 'href' => 'OLDAP-1.4.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.0' => [ 'id' => 'OLDAP-2.0', 'fullname' => 'Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)', 'href' => 'OLDAP-2.0.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.0.1' => [ 'id' => 'OLDAP-2.0.1', 'fullname' => 'Open LDAP Public License v2.0.1', 'href' => 'OLDAP-2.0.1.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.1' => [ 'id' => 'OLDAP-2.1', 'fullname' => 'Open LDAP Public License v2.1', 'href' => 'OLDAP-2.1.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.2' => [ 'id' => 'OLDAP-2.2', 'fullname' => 'Open LDAP Public License v2.2', 'href' => 'OLDAP-2.2.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.2.1' => [ 'id' => 'OLDAP-2.2.1', 'fullname' => 'Open LDAP Public License v2.2.1', 'href' => 'OLDAP-2.2.1.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.2.2' => [ 'id' => 'OLDAP-2.2.2', 'fullname' => 'Open LDAP Public License 2.2.2', 'href' => 'OLDAP-2.2.2.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.3' => [ 'id' => 'OLDAP-2.3', 'fullname' => 'Open LDAP Public License v2.3', 'href' => 'OLDAP-2.3.html', 'free' => true, 'osi' => false ],
		'OLDAP-2.4' => [ 'id' => 'OLDAP-2.4', 'fullname' => 'Open LDAP Public License v2.4', 'href' => 'OLDAP-2.4.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.5' => [ 'id' => 'OLDAP-2.5', 'fullname' => 'Open LDAP Public License v2.5', 'href' => 'OLDAP-2.5.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.6' => [ 'id' => 'OLDAP-2.6', 'fullname' => 'Open LDAP Public License v2.6', 'href' => 'OLDAP-2.6.html', 'free' => false, 'osi' => false ],
		'OLDAP-2.7' => [ 'id' => 'OLDAP-2.7', 'fullname' => 'Open LDAP Public License v2.7', 'href' => 'OLDAP-2.7.html', 'free' => true, 'osi' => false ],
		'OLDAP-2.8' => [ 'id' => 'OLDAP-2.8', 'fullname' => 'Open LDAP Public License v2.8', 'href' => 'OLDAP-2.8.html', 'free' => false, 'osi' => true ],
		'OML' => [ 'id' => 'OML', 'fullname' => 'Open Market License', 'href' => 'OML.html', 'free' => false, 'osi' => false ],
		'OpenPBS-2.3' => [ 'id' => 'OpenPBS-2.3', 'fullname' => 'OpenPBS v2.3 Software License', 'href' => 'OpenPBS-2.3.html', 'free' => false, 'osi' => false ],
		'OpenSSL' => [ 'id' => 'OpenSSL', 'fullname' => 'OpenSSL License', 'href' => 'OpenSSL.html', 'free' => true, 'osi' => false ],
		'OPL-1.0' => [ 'id' => 'OPL-1.0', 'fullname' => 'Open Public License v1.0', 'href' => 'OPL-1.0.html', 'free' => false, 'osi' => false ],
		'OPUBL-1.0' => [ 'id' => 'OPUBL-1.0', 'fullname' => 'Open Publication License v1.0', 'href' => 'OPUBL-1.0.html', 'free' => false, 'osi' => false ],
		'OSET-PL-2.1' => [ 'id' => 'OSET-PL-2.1', 'fullname' => 'OSET Public License version 2.1', 'href' => 'OSET-PL-2.1.html', 'free' => false, 'osi' => true ],
		'OSL-1.0' => [ 'id' => 'OSL-1.0', 'fullname' => 'Open Software License 1.0', 'href' => 'OSL-1.0.html', 'free' => true, 'osi' => true ],
		'OSL-1.1' => [ 'id' => 'OSL-1.1', 'fullname' => 'Open Software License 1.1', 'href' => 'OSL-1.1.html', 'free' => true, 'osi' => false ],
		'OSL-2.0' => [ 'id' => 'OSL-2.0', 'fullname' => 'Open Software License 2.0', 'href' => 'OSL-2.0.html', 'free' => true, 'osi' => true ],
		'OSL-2.1' => [ 'id' => 'OSL-2.1', 'fullname' => 'Open Software License 2.1', 'href' => 'OSL-2.1.html', 'free' => true, 'osi' => true ],
		'OSL-3.0' => [ 'id' => 'OSL-3.0', 'fullname' => 'Open Software License 3.0', 'href' => 'OSL-3.0.html', 'free' => true, 'osi' => true ],
		'Parity-6.0.0' => [ 'id' => 'Parity-6.0.0', 'fullname' => 'The Parity Public License 6.0.0', 'href' => 'Parity-6.0.0.html', 'free' => false, 'osi' => false ],
		'Parity-7.0.0' => [ 'id' => 'Parity-7.0.0', 'fullname' => 'The Parity Public License 7.0.0', 'href' => 'Parity-7.0.0.html', 'free' => false, 'osi' => false ],
		'PDDL-1.0' => [ 'id' => 'PDDL-1.0', 'fullname' => 'Open Data Commons Public Domain Dedication &amp; License 1.0', 'href' => 'PDDL-1.0.html', 'free' => false, 'osi' => false ],
		'PHP-3.0' => [ 'id' => 'PHP-3.0', 'fullname' => 'PHP License v3.0', 'href' => 'PHP-3.0.html', 'free' => false, 'osi' => true ],
		'PHP-3.01' => [ 'id' => 'PHP-3.01', 'fullname' => 'PHP License v3.01', 'href' => 'PHP-3.01.html', 'free' => true, 'osi' => true ],
		'Plexus' => [ 'id' => 'Plexus', 'fullname' => 'Plexus Classworlds License', 'href' => 'Plexus.html', 'free' => false, 'osi' => false ],
		'PolyForm-Noncommercial-1.0.0' => [ 'id' => 'PolyForm-Noncommercial-1.0.0', 'fullname' => 'PolyForm Noncommercial License 1.0.0', 'href' => 'PolyForm-Noncommercial-1.0.0.html', 'free' => false, 'osi' => false ],
		'PolyForm-Small-Business-1.0.0' => [ 'id' => 'PolyForm-Small-Business-1.0.0', 'fullname' => 'PolyForm Small Business License 1.0.0', 'href' => 'PolyForm-Small-Business-1.0.0.html', 'free' => false, 'osi' => false ],
		'PostgreSQL' => [ 'id' => 'PostgreSQL', 'fullname' => 'PostgreSQL License', 'href' => 'PostgreSQL.html', 'free' => false, 'osi' => true ],
		'PSF-2.0' => [ 'id' => 'PSF-2.0', 'fullname' => 'Python Software Foundation License 2.0', 'href' => 'PSF-2.0.html', 'free' => false, 'osi' => false ],
		'psfrag' => [ 'id' => 'psfrag', 'fullname' => 'psfrag License', 'href' => 'psfrag.html', 'free' => false, 'osi' => false ],
		'psutils' => [ 'id' => 'psutils', 'fullname' => 'psutils License', 'href' => 'psutils.html', 'free' => false, 'osi' => false ],
		'Python-2.0' => [ 'id' => 'Python-2.0', 'fullname' => 'Python License 2.0', 'href' => 'Python-2.0.html', 'free' => true, 'osi' => true ],
		'Python-2.0.1' => [ 'id' => 'Python-2.0.1', 'fullname' => 'Python License 2.0.1', 'href' => 'Python-2.0.1.html', 'free' => false, 'osi' => false ],
		'Qhull' => [ 'id' => 'Qhull', 'fullname' => 'Qhull License', 'href' => 'Qhull.html', 'free' => false, 'osi' => false ],
		'QPL-1.0' => [ 'id' => 'QPL-1.0', 'fullname' => 'Q Public License 1.0', 'href' => 'QPL-1.0.html', 'free' => true, 'osi' => true ],
		'QPL-1.0-INRIA-2004' => [ 'id' => 'QPL-1.0-INRIA-2004', 'fullname' => 'Q Public License 1.0 - INRIA 2004 variant', 'href' => 'QPL-1.0-INRIA-2004.html', 'free' => false, 'osi' => false ],
		'Rdisc' => [ 'id' => 'Rdisc', 'fullname' => 'Rdisc License', 'href' => 'Rdisc.html', 'free' => false, 'osi' => false ],
		'RHeCos-1.1' => [ 'id' => 'RHeCos-1.1', 'fullname' => 'Red Hat eCos Public License v1.1', 'href' => 'RHeCos-1.1.html', 'free' => false, 'osi' => false ],
		'RPL-1.1' => [ 'id' => 'RPL-1.1', 'fullname' => 'Reciprocal Public License 1.1', 'href' => 'RPL-1.1.html', 'free' => false, 'osi' => true ],
		'RPL-1.5' => [ 'id' => 'RPL-1.5', 'fullname' => 'Reciprocal Public License 1.5', 'href' => 'RPL-1.5.html', 'free' => false, 'osi' => true ],
		'RPSL-1.0' => [ 'id' => 'RPSL-1.0', 'fullname' => 'RealNetworks Public Source License v1.0', 'href' => 'RPSL-1.0.html', 'free' => true, 'osi' => true ],
		'RSA-MD' => [ 'id' => 'RSA-MD', 'fullname' => 'RSA Message-Digest License', 'href' => 'RSA-MD.html', 'free' => false, 'osi' => false ],
		'RSCPL' => [ 'id' => 'RSCPL', 'fullname' => 'Ricoh Source Code Public License', 'href' => 'RSCPL.html', 'free' => false, 'osi' => true ],
		'Ruby' => [ 'id' => 'Ruby', 'fullname' => 'Ruby License', 'href' => 'Ruby.html', 'free' => true, 'osi' => false ],
		'SAX-PD' => [ 'id' => 'SAX-PD', 'fullname' => 'Sax Public Domain Notice', 'href' => 'SAX-PD.html', 'free' => false, 'osi' => false ],
		'Saxpath' => [ 'id' => 'Saxpath', 'fullname' => 'Saxpath License', 'href' => 'Saxpath.html', 'free' => false, 'osi' => false ],
		'SCEA' => [ 'id' => 'SCEA', 'fullname' => 'SCEA Shared Source License', 'href' => 'SCEA.html', 'free' => false, 'osi' => false ],
		'SchemeReport' => [ 'id' => 'SchemeReport', 'fullname' => 'Scheme Language Report License', 'href' => 'SchemeReport.html', 'free' => false, 'osi' => false ],
		'Sendmail' => [ 'id' => 'Sendmail', 'fullname' => 'Sendmail License', 'href' => 'Sendmail.html', 'free' => false, 'osi' => false ],
		'Sendmail-8.23' => [ 'id' => 'Sendmail-8.23', 'fullname' => 'Sendmail License 8.23', 'href' => 'Sendmail-8.23.html', 'free' => false, 'osi' => false ],
		'SGI-B-1.0' => [ 'id' => 'SGI-B-1.0', 'fullname' => 'SGI Free Software License B v1.0', 'href' => 'SGI-B-1.0.html', 'free' => false, 'osi' => false ],
		'SGI-B-1.1' => [ 'id' => 'SGI-B-1.1', 'fullname' => 'SGI Free Software License B v1.1', 'href' => 'SGI-B-1.1.html', 'free' => false, 'osi' => false ],
		'SGI-B-2.0' => [ 'id' => 'SGI-B-2.0', 'fullname' => 'SGI Free Software License B v2.0', 'href' => 'SGI-B-2.0.html', 'free' => true, 'osi' => false ],
		'SHL-0.5' => [ 'id' => 'SHL-0.5', 'fullname' => 'Solderpad Hardware License v0.5', 'href' => 'SHL-0.5.html', 'free' => false, 'osi' => false ],
		'SHL-0.51' => [ 'id' => 'SHL-0.51', 'fullname' => 'Solderpad Hardware License, Version 0.51', 'href' => 'SHL-0.51.html', 'free' => false, 'osi' => false ],
		'SimPL-2.0' => [ 'id' => 'SimPL-2.0', 'fullname' => 'Simple Public License 2.0', 'href' => 'SimPL-2.0.html', 'free' => false, 'osi' => true ],
		'SISSL' => [ 'id' => 'SISSL', 'fullname' => 'Sun Industry Standards Source License v1.1', 'href' => 'SISSL.html', 'free' => true, 'osi' => true ],
		'SISSL-1.2' => [ 'id' => 'SISSL-1.2', 'fullname' => 'Sun Industry Standards Source License v1.2', 'href' => 'SISSL-1.2.html', 'free' => false, 'osi' => false ],
		'Sleepycat' => [ 'id' => 'Sleepycat', 'fullname' => 'Sleepycat License', 'href' => 'Sleepycat.html', 'free' => true, 'osi' => true ],
		'SMLNJ' => [ 'id' => 'SMLNJ', 'fullname' => 'Standard ML of New Jersey License', 'href' => 'SMLNJ.html', 'free' => true, 'osi' => false ],
		'SMPPL' => [ 'id' => 'SMPPL', 'fullname' => 'Secure Messaging Protocol Public License', 'href' => 'SMPPL.html', 'free' => false, 'osi' => false ],
		'SNIA' => [ 'id' => 'SNIA', 'fullname' => 'SNIA Public License 1.1', 'href' => 'SNIA.html', 'free' => false, 'osi' => false ],
		'snprintf' => [ 'id' => 'snprintf', 'fullname' => 'snprintf License', 'href' => 'snprintf.html', 'free' => false, 'osi' => false ],
		'Spencer-86' => [ 'id' => 'Spencer-86', 'fullname' => 'Spencer License 86', 'href' => 'Spencer-86.html', 'free' => false, 'osi' => false ],
		'Spencer-94' => [ 'id' => 'Spencer-94', 'fullname' => 'Spencer License 94', 'href' => 'Spencer-94.html', 'free' => false, 'osi' => false ],
		'Spencer-99' => [ 'id' => 'Spencer-99', 'fullname' => 'Spencer License 99', 'href' => 'Spencer-99.html', 'free' => false, 'osi' => false ],
		'SPL-1.0' => [ 'id' => 'SPL-1.0', 'fullname' => 'Sun Public License v1.0', 'href' => 'SPL-1.0.html', 'free' => true, 'osi' => true ],
		'SSH-OpenSSH' => [ 'id' => 'SSH-OpenSSH', 'fullname' => 'SSH OpenSSH license', 'href' => 'SSH-OpenSSH.html', 'free' => false, 'osi' => false ],
		'SSH-short' => [ 'id' => 'SSH-short', 'fullname' => 'SSH short notice', 'href' => 'SSH-short.html', 'free' => false, 'osi' => false ],
		'SSPL-1.0' => [ 'id' => 'SSPL-1.0', 'fullname' => 'Server Side Public License, v 1', 'href' => 'SSPL-1.0.html', 'free' => false, 'osi' => false ],
		'SugarCRM-1.1.3' => [ 'id' => 'SugarCRM-1.1.3', 'fullname' => 'SugarCRM Public License v1.1.3', 'href' => 'SugarCRM-1.1.3.html', 'free' => false, 'osi' => false ],
		'SunPro' => [ 'id' => 'SunPro', 'fullname' => 'SunPro License', 'href' => 'SunPro.html', 'free' => false, 'osi' => false ],
		'SWL' => [ 'id' => 'SWL', 'fullname' => 'Scheme Widget Library (SWL) Software License Agreement', 'href' => 'SWL.html', 'free' => false, 'osi' => false ],
		'Symlinks' => [ 'id' => 'Symlinks', 'fullname' => 'Symlinks License', 'href' => 'Symlinks.html', 'free' => false, 'osi' => false ],
		'TAPR-OHL-1.0' => [ 'id' => 'TAPR-OHL-1.0', 'fullname' => 'TAPR Open Hardware License v1.0', 'href' => 'TAPR-OHL-1.0.html', 'free' => false, 'osi' => false ],
		'TCL' => [ 'id' => 'TCL', 'fullname' => 'TCL/TK License', 'href' => 'TCL.html', 'free' => false, 'osi' => false ],
		'TCP-wrappers' => [ 'id' => 'TCP-wrappers', 'fullname' => 'TCP Wrappers License', 'href' => 'TCP-wrappers.html', 'free' => false, 'osi' => false ],
		'TMate' => [ 'id' => 'TMate', 'fullname' => 'TMate Open Source License', 'href' => 'TMate.html', 'free' => false, 'osi' => false ],
		'TORQUE-1.1' => [ 'id' => 'TORQUE-1.1', 'fullname' => 'TORQUE v2.5+ Software License v1.1', 'href' => 'TORQUE-1.1.html', 'free' => false, 'osi' => false ],
		'TOSL' => [ 'id' => 'TOSL', 'fullname' => 'Trusster Open Source License', 'href' => 'TOSL.html', 'free' => false, 'osi' => false ],
		'TPDL' => [ 'id' => 'TPDL', 'fullname' => 'Time::ParseDate License', 'href' => 'TPDL.html', 'free' => false, 'osi' => false ],
		'TPL-1.0' => [ 'id' => 'TPL-1.0', 'fullname' => 'THOR Public License 1.0', 'href' => 'TPL-1.0.html', 'free' => false, 'osi' => false ],
		'TTWL' => [ 'id' => 'TTWL', 'fullname' => 'Text-Tabs+Wrap License', 'href' => 'TTWL.html', 'free' => false, 'osi' => false ],
		'TU-Berlin-1.0' => [ 'id' => 'TU-Berlin-1.0', 'fullname' => 'Technische Universitaet Berlin License 1.0', 'href' => 'TU-Berlin-1.0.html', 'free' => false, 'osi' => false ],
		'TU-Berlin-2.0' => [ 'id' => 'TU-Berlin-2.0', 'fullname' => 'Technische Universitaet Berlin License 2.0', 'href' => 'TU-Berlin-2.0.html', 'free' => false, 'osi' => false ],
		'UCAR' => [ 'id' => 'UCAR', 'fullname' => 'UCAR License', 'href' => 'UCAR.html', 'free' => false, 'osi' => false ],
		'UCL-1.0' => [ 'id' => 'UCL-1.0', 'fullname' => 'Upstream Compatibility License v1.0', 'href' => 'UCL-1.0.html', 'free' => false, 'osi' => true ],
		'Unicode-DFS-2015' => [ 'id' => 'Unicode-DFS-2015', 'fullname' => 'Unicode License Agreement - Data Files and Software (2015)', 'href' => 'Unicode-DFS-2015.html', 'free' => false, 'osi' => false ],
		'Unicode-DFS-2016' => [ 'id' => 'Unicode-DFS-2016', 'fullname' => 'Unicode License Agreement - Data Files and Software (2016)', 'href' => 'Unicode-DFS-2016.html', 'free' => false, 'osi' => true ],
		'Unicode-TOU' => [ 'id' => 'Unicode-TOU', 'fullname' => 'Unicode Terms of Use', 'href' => 'Unicode-TOU.html', 'free' => false, 'osi' => false ],
		'Unlicense' => [ 'id' => 'Unlicense', 'fullname' => 'The Unlicense', 'href' => 'Unlicense.html', 'free' => true, 'osi' => true ],
		'UPL-1.0' => [ 'id' => 'UPL-1.0', 'fullname' => 'Universal Permissive License v1.0', 'href' => 'UPL-1.0.html', 'free' => true, 'osi' => true ],
		'Vim' => [ 'id' => 'Vim', 'fullname' => 'Vim License', 'href' => 'Vim.html', 'free' => true, 'osi' => false ],
		'VOSTROM' => [ 'id' => 'VOSTROM', 'fullname' => 'VOSTROM Public License for Open Source', 'href' => 'VOSTROM.html', 'free' => false, 'osi' => false ],
		'VSL-1.0' => [ 'id' => 'VSL-1.0', 'fullname' => 'Vovida Software License v1.0', 'href' => 'VSL-1.0.html', 'free' => false, 'osi' => true ],
		'W3C' => [ 'id' => 'W3C', 'fullname' => 'W3C Software Notice and License (2002-12-31)', 'href' => 'W3C.html', 'free' => true, 'osi' => true ],
		'W3C-19980720' => [ 'id' => 'W3C-19980720', 'fullname' => 'W3C Software Notice and License (1998-07-20)', 'href' => 'W3C-19980720.html', 'free' => false, 'osi' => false ],
		'W3C-20150513' => [ 'id' => 'W3C-20150513', 'fullname' => 'W3C Software Notice and Document License (2015-05-13)', 'href' => 'W3C-20150513.html', 'free' => false, 'osi' => false ],
		'w3m' => [ 'id' => 'w3m', 'fullname' => 'w3m License', 'href' => 'w3m.html', 'free' => false, 'osi' => false ],
		'Watcom-1.0' => [ 'id' => 'Watcom-1.0', 'fullname' => 'Sybase Open Watcom Public License 1.0', 'href' => 'Watcom-1.0.html', 'free' => false, 'osi' => true ],
		'Wsuipa' => [ 'id' => 'Wsuipa', 'fullname' => 'Wsuipa License', 'href' => 'Wsuipa.html', 'free' => false, 'osi' => false ],
		'WTFPL' => [ 'id' => 'WTFPL', 'fullname' => 'Do What The F*ck You Want To Public License', 'href' => 'WTFPL.html', 'free' => true, 'osi' => false ],
		'X11' => [ 'id' => 'X11', 'fullname' => 'X11 License', 'href' => 'X11.html', 'free' => true, 'osi' => false ],
		'X11-distribute-modifications-variant' => [ 'id' => 'X11-distribute-modifications-variant', 'fullname' => 'X11 License Distribution Modification Variant', 'href' => 'X11-distribute-modifications-variant.html', 'free' => false, 'osi' => false ],
		'Xerox' => [ 'id' => 'Xerox', 'fullname' => 'Xerox License', 'href' => 'Xerox.html', 'free' => false, 'osi' => false ],
		'XFree86-1.1' => [ 'id' => 'XFree86-1.1', 'fullname' => 'XFree86 License 1.1', 'href' => 'XFree86-1.1.html', 'free' => true, 'osi' => false ],
		'xinetd' => [ 'id' => 'xinetd', 'fullname' => 'xinetd License', 'href' => 'xinetd.html', 'free' => true, 'osi' => false ],
		'xlock' => [ 'id' => 'xlock', 'fullname' => 'xlock License', 'href' => 'xlock.html', 'free' => false, 'osi' => false ],
		'Xnet' => [ 'id' => 'Xnet', 'fullname' => 'X.Net License', 'href' => 'Xnet.html', 'free' => false, 'osi' => true ],
		'xpp' => [ 'id' => 'xpp', 'fullname' => 'XPP License', 'href' => 'xpp.html', 'free' => false, 'osi' => false ],
		'XSkat' => [ 'id' => 'XSkat', 'fullname' => 'XSkat License', 'href' => 'XSkat.html', 'free' => false, 'osi' => false ],
		'YPL-1.0' => [ 'id' => 'YPL-1.0', 'fullname' => 'Yahoo! Public License v1.0', 'href' => 'YPL-1.0.html', 'free' => false, 'osi' => false ],
		'YPL-1.1' => [ 'id' => 'YPL-1.1', 'fullname' => 'Yahoo! Public License v1.1', 'href' => 'YPL-1.1.html', 'free' => true, 'osi' => false ],
		'Zed' => [ 'id' => 'Zed', 'fullname' => 'Zed License', 'href' => 'Zed.html', 'free' => false, 'osi' => false ],
		'Zend-2.0' => [ 'id' => 'Zend-2.0', 'fullname' => 'Zend License v2.0', 'href' => 'Zend-2.0.html', 'free' => true, 'osi' => false ],
		'Zimbra-1.3' => [ 'id' => 'Zimbra-1.3', 'fullname' => 'Zimbra Public License v1.3', 'href' => 'Zimbra-1.3.html', 'free' => true, 'osi' => false ],
		'Zimbra-1.4' => [ 'id' => 'Zimbra-1.4', 'fullname' => 'Zimbra Public License v1.4', 'href' => 'Zimbra-1.4.html', 'free' => false, 'osi' => false ],
		'Zlib' => [ 'id' => 'Zlib', 'fullname' => 'zlib License', 'href' => 'Zlib.html', 'free' => true, 'osi' => true ],
		'zlib-acknowledgement' => [ 'id' => 'zlib-acknowledgement', 'fullname' => 'zlib/libpng License with Acknowledgement', 'href' => 'zlib-acknowledgement.html', 'free' => false, 'osi' => false ],
		'ZPL-1.1' => [ 'id' => 'ZPL-1.1', 'fullname' => 'Zope Public License 1.1', 'href' => 'ZPL-1.1.html', 'free' => false, 'osi' => false ],
		'ZPL-2.0' => [ 'id' => 'ZPL-2.0', 'fullname' => 'Zope Public License 2.0', 'href' => 'ZPL-2.0.html', 'free' => true, 'osi' => true ],
		'ZPL-2.1' => [ 'id' => 'ZPL-2.1', 'fullname' => 'Zope Public License 2.1', 'href' => 'ZPL-2.1.html', 'free' => true, 'osi' => true ],
	
		/* deprecated identifiers */
		'Public Domain' => [ 'id' => 'Public Domain', 'fullname' => 'Public Domain', 'href' => 'PD.html', 'free' => false, 'osi' => false ],
		'Public-Domain' => [ 'id' => 'Public Domain', 'fullname' => 'Public Domain', 'href' => 'PD.html', 'free' => false, 'osi' => false ],
		'Shareware' => [ 'id' => 'Shareware', 'fullname' => 'Shareware', 'href' => 'Shareware.html', 'free' => false, 'osi' => false ],
		'AGPL-1.0' => [ 'id' => 'AGPL-1.0', 'fullname' => 'Affero General Public License v1.0', 'href' => 'AGPL-1.0.html', 'free' => false, 'osi' => false ],
		'AGPL-3.0' => [ 'id' => 'AGPL-3.0', 'fullname' => 'GNU Affero General Public License v3.0', 'href' => 'AGPL-3.0.html', 'free' => true, 'osi' => true ],
		'BSD-2-Clause-FreeBSD' => [ 'id' => 'BSD-2-Clause-FreeBSD', 'fullname' => 'BSD 2-Clause FreeBSD License', 'href' => 'BSD-2-Clause-FreeBSD.html', 'free' => true, 'osi' => true ],
		'BSD-2-Clause-NetBSD' => [ 'id' => 'BSD-2-Clause-NetBSD', 'fullname' => 'BSD 2-Clause NetBSD License', 'href' => 'BSD-2-Clause-NetBSD.html', 'free' => true, 'osi' => true ],
		'bzip2-1.0.5' => [ 'id' => 'bzip2-1.0.5', 'fullname' => 'bzip2 and libbzip2 License v1.0.5', 'href' => 'bzip2-1.0.5.html', 'free' => false, 'osi' => false ],
		'eCos-2.0' => [ 'id' => 'eCos-2.0', 'fullname' => 'eCos license version 2.0', 'href' => 'eCos-2.0.html', 'free' => false, 'osi' => false ],
		'GFDL-1.1' => [ 'id' => 'GFDL-1.1', 'fullname' => 'GNU Free Documentation License v1.1', 'href' => 'GFDL-1.1.html', 'free' => true, 'osi' => false ],
		'GFDL-1.2' => [ 'id' => 'GFDL-1.2', 'fullname' => 'GNU Free Documentation License v1.2', 'href' => 'GFDL-1.2.html', 'free' => true, 'osi' => false ],
		'GFDL-1.3' => [ 'id' => 'GFDL-1.3', 'fullname' => 'GNU Free Documentation License v1.3', 'href' => 'GFDL-1.3.html', 'free' => true, 'osi' => false ],
		'GPL-1.0' => [ 'id' => 'GPL-1.0', 'fullname' => 'GNU General Public License v1.0 only', 'href' => 'GPL-1.0.html', 'free' => false, 'osi' => false ],
		'GPL-1.0+' => [ 'id' => 'GPL-1.0+', 'fullname' => 'GNU General Public License v1.0 or later', 'href' => 'GPL-1.0+.html', 'free' => false, 'osi' => false ],
		'GPL-2.0' => [ 'id' => 'GPL-2.0', 'fullname' => 'GNU General Public License v2.0 only', 'href' => 'GPL-2.0.html', 'free' => true, 'osi' => true ],
		'GPL-2.0+' => [ 'id' => 'GPL-2.0+', 'fullname' => 'GNU General Public License v2.0 or later', 'href' => 'GPL-2.0+.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-with-autoconf-exception' => [ 'id' => 'GPL-2.0-with-autoconf-exception', 'fullname' => 'GNU General Public License v2.0 w/Autoconf exception', 'href' => 'GPL-2.0-with-autoconf-exception.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-with-bison-exception' => [ 'id' => 'GPL-2.0-with-bison-exception', 'fullname' => 'GNU General Public License v2.0 w/Bison exception', 'href' => 'GPL-2.0-with-bison-exception.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-with-classpath-exception' => [ 'id' => 'GPL-2.0-with-classpath-exception', 'fullname' => 'GNU General Public License v2.0 w/Classpath exception', 'href' => 'GPL-2.0-with-classpath-exception.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-with-font-exception' => [ 'id' => 'GPL-2.0-with-font-exception', 'fullname' => 'GNU General Public License v2.0 w/Font exception', 'href' => 'GPL-2.0-with-font-exception.html', 'free' => true, 'osi' => true ],
		'GPL-2.0-with-GCC-exception' => [ 'id' => 'GPL-2.0-with-GCC-exception', 'fullname' => 'GNU General Public License v2.0 w/GCC Runtime Library exception', 'href' => 'GPL-2.0-with-GCC-exception.html', 'free' => true, 'osi' => true ],
		'GPL-3.0' => [ 'id' => 'GPL-3.0', 'fullname' => 'GNU General Public License v3.0 only', 'href' => 'GPL-3.0.html', 'free' => true, 'osi' => true ],
		'GPL-3.0+' => [ 'id' => 'GPL-3.0+', 'fullname' => 'GNU General Public License v3.0 or later', 'href' => 'GPL-3.0+.html', 'free' => true, 'osi' => true ],
		'GPL-3.0-with-autoconf-exception' => [ 'id' => 'GPL-3.0-with-autoconf-exception', 'fullname' => 'GNU General Public License v3.0 w/Autoconf exception', 'href' => 'GPL-3.0-with-autoconf-exception.html', 'free' => true, 'osi' => true ],
		'GPL-3.0-with-GCC-exception' => [ 'id' => 'GPL-3.0-with-GCC-exception', 'fullname' => 'GNU General Public License v3.0 w/GCC Runtime Library exception', 'href' => 'GPL-3.0-with-GCC-exception.html', 'free' => true, 'osi' => true ],
		'LGPL-2.0' => [ 'id' => 'LGPL-2.0', 'fullname' => 'GNU Library General Public License v2 only', 'href' => 'LGPL-2.0.html', 'free' => false, 'osi' => true ],
		'LGPL-2.0+' => [ 'id' => 'LGPL-2.0+', 'fullname' => 'GNU Library General Public License v2 or later', 'href' => 'LGPL-2.0+.html', 'free' => false, 'osi' => true ],
		'LGPL-2.1' => [ 'id' => 'LGPL-2.1', 'fullname' => 'GNU Lesser General Public License v2.1 only', 'href' => 'LGPL-2.1.html', 'free' => true, 'osi' => true ],
		'LGPL-2.1+' => [ 'id' => 'LGPL-2.1+', 'fullname' => 'GNU Lesser General Public License v2.1 or later', 'href' => 'LGPL-2.1+.html', 'free' => true, 'osi' => true ],
		'LGPL-3.0' => [ 'id' => 'LGPL-3.0', 'fullname' => 'GNU Lesser General Public License v3.0 only', 'href' => 'LGPL-3.0.html', 'free' => true, 'osi' => true ],
		'LGPL-3.0+' => [ 'id' => 'LGPL-3.0+', 'fullname' => 'GNU Lesser General Public License v3.0 or later', 'href' => 'LGPL-3.0+.html', 'free' => true, 'osi' => true ],
		'Nunit' => [ 'id' => 'Nunit', 'fullname' => 'Nunit License', 'href' => 'Nunit.html', 'free' => false, 'osi' => false ],
		'StandardML-NJ' => [ 'id' => 'StandardML-NJ', 'fullname' => 'Standard ML of New Jersey License', 'href' => 'StandardML-NJ.html', 'free' => false, 'osi' => false ],
		'wxWindows' => [ 'id' => 'wxWindows', 'fullname' => 'wxWindows Library License', 'href' => 'wxWindows.html', 'free' => false, 'osi' => false ],
	);

	public static $license_exceptions = array(
		'389-exception' => [ 'id' => '389-exception', 'fullname' => '389 Directory Server Exception', 'href' => '389-exception.html' ],
		'Autoconf-exception-2.0' => [ 'id' => 'Autoconf-exception-2.0', 'fullname' => 'Autoconf exception 2.0', 'href' => 'Autoconf-exception-2.0.html' ],
		'Autoconf-exception-3.0' => [ 'id' => 'Autoconf-exception-3.0', 'fullname' => 'Autoconf exception 3.0', 'href' => 'Autoconf-exception-3.0.html' ],
		'Autoconf-exception-generic' => [ 'id' => 'Autoconf-exception-generic', 'fullname' => 'Autoconf generic exception', 'href' => 'Autoconf-exception-generic.html' ],
		'Bison-exception-2.2' => [ 'id' => 'Bison-exception-2.2', 'fullname' => 'Bison exception 2.2', 'href' => 'Bison-exception-2.2.html' ],
		'Bootloader-exception' => [ 'id' => 'Bootloader-exception', 'fullname' => 'Bootloader Distribution Exception', 'href' => 'Bootloader-exception.html' ],
		'Classpath-exception-2.0' => [ 'id' => 'Classpath-exception-2.0', 'fullname' => 'Classpath exception 2.0', 'href' => 'Classpath-exception-2.0.html' ],
		'CLISP-exception-2.0' => [ 'id' => 'CLISP-exception-2.0', 'fullname' => 'CLISP exception 2.0', 'href' => 'CLISP-exception-2.0.html' ],
		'DigiRule-FOSS-exception' => [ 'id' => 'DigiRule-FOSS-exception', 'fullname' => 'DigiRule FOSS License Exception', 'href' => 'DigiRule-FOSS-exception.html' ],
		'eCos-exception-2.0' => [ 'id' => 'eCos-exception-2.0', 'fullname' => 'eCos exception 2.0', 'href' => 'eCos-exception-2.0.html' ],
		'Fawkes-Runtime-exception' => [ 'id' => 'Fawkes-Runtime-exception', 'fullname' => 'Fawkes Runtime Exception', 'href' => 'Fawkes-Runtime-exception.html' ],
		'FLTK-exception' => [ 'id' => 'FLTK-exception', 'fullname' => 'FLTK exception', 'href' => 'FLTK-exception.html' ],
		'Font-exception-2.0' => [ 'id' => 'Font-exception-2.0', 'fullname' => 'Font exception 2.0', 'href' => 'Font-exception-2.0.html' ],
		'freertos-exception-2.0' => [ 'id' => 'freertos-exception-2.0', 'fullname' => 'FreeRTOS Exception 2.0', 'href' => 'freertos-exception-2.0.html' ],
		'GCC-exception-2.0' => [ 'id' => 'GCC-exception-2.0', 'fullname' => 'GCC Runtime Library exception 2.0', 'href' => 'GCC-exception-2.0.html' ],
		'GCC-exception-3.1' => [ 'id' => 'GCC-exception-3.1', 'fullname' => 'GCC Runtime Library exception 3.1', 'href' => 'GCC-exception-3.1.html' ],
		'GNAT-exception' => [ 'id' => 'GNAT-exception', 'fullname' => 'GNAT exception', 'href' => 'GNAT-exception.html' ],
		'gnu-javamail-exception' => [ 'id' => 'gnu-javamail-exception', 'fullname' => 'GNU JavaMail exception', 'href' => 'gnu-javamail-exception.html' ],
		'GPL-3.0-linking-exception' => [ 'id' => 'GPL-3.0-linking-exception', 'fullname' => 'GPL-3.0 Linking Exception', 'href' => 'GPL-3.0-linking-exception.html' ],
		'GPL-3.0-linking-source-exception' => [ 'id' => 'GPL-3.0-linking-source-exception', 'fullname' => 'GPL-3.0 Linking Exception (with Corresponding Source)', 'href' => 'GPL-3.0-linking-source-exception.html' ],
		'GPL-CC-1.0' => [ 'id' => 'GPL-CC-1.0', 'fullname' => 'GPL Cooperation Commitment 1.0', 'href' => 'GPL-CC-1.0.html' ],
		'GStreamer-exception-2005' => [ 'id' => 'GStreamer-exception-2005', 'fullname' => 'GStreamer Exception (2005)', 'href' => 'GStreamer-exception-2005.html' ],
		'GStreamer-exception-2008' => [ 'id' => 'GStreamer-exception-2008', 'fullname' => 'GStreamer Exception (2008)', 'href' => 'GStreamer-exception-2008.html' ],
		'i2p-gpl-java-exception' => [ 'id' => 'i2p-gpl-java-exception', 'fullname' => 'i2p GPL+Java Exception', 'href' => 'i2p-gpl-java-exception.html' ],
		'KiCad-libraries-exception' => [ 'id' => 'KiCad-libraries-exception', 'fullname' => 'KiCad Libraries Exception', 'href' => 'KiCad-libraries-exception.html' ],
		'LGPL-3.0-linking-exception' => [ 'id' => 'LGPL-3.0-linking-exception', 'fullname' => 'LGPL-3.0 Linking Exception', 'href' => 'LGPL-3.0-linking-exception.html' ],
		'Libtool-exception' => [ 'id' => 'Libtool-exception', 'fullname' => 'Libtool Exception', 'href' => 'Libtool-exception.html' ],
		'Linux-syscall-note' => [ 'id' => 'Linux-syscall-note', 'fullname' => 'Linux Syscall Note', 'href' => 'Linux-syscall-note.html' ],
		'LLVM-exception' => [ 'id' => 'LLVM-exception', 'fullname' => 'LLVM Exception', 'href' => 'LLVM-exception.html' ],
		'LZMA-exception' => [ 'id' => 'LZMA-exception', 'fullname' => 'LZMA exception', 'href' => 'LZMA-exception.html' ],
		'mif-exception' => [ 'id' => 'mif-exception', 'fullname' => 'Macros and Inline Functions Exception', 'href' => 'mif-exception.html' ],
		'OCaml-LGPL-linking-exception' => [ 'id' => 'OCaml-LGPL-linking-exception', 'fullname' => 'OCaml LGPL Linking Exception', 'href' => 'OCaml-LGPL-linking-exception.html' ],
		'OCCT-exception-1.0' => [ 'id' => 'OCCT-exception-1.0', 'fullname' => 'Open CASCADE Exception 1.0', 'href' => 'OCCT-exception-1.0.html' ],
		'OpenJDK-assembly-exception-1.0' => [ 'id' => 'OpenJDK-assembly-exception-1.0', 'fullname' => 'OpenJDK Assembly exception 1.0', 'href' => 'OpenJDK-assembly-exception-1.0.html' ],
		'openvpn-openssl-exception' => [ 'id' => 'openvpn-openssl-exception', 'fullname' => 'OpenVPN OpenSSL Exception', 'href' => 'openvpn-openssl-exception.html' ],
		'PS-or-PDF-font-exception-20170817' => [ 'id' => 'PS-or-PDF-font-exception-20170817', 'fullname' => 'PS/PDF font exception (2017-08-17)', 'href' => 'PS-or-PDF-font-exception-20170817.html' ],
		'QPL-1.0-INRIA-2004-exception' => [ 'id' => 'QPL-1.0-INRIA-2004-exception', 'fullname' => 'INRIA QPL 1.0 2004 variant exception', 'href' => 'QPL-1.0-INRIA-2004-exception.html' ],
		'Qt-GPL-exception-1.0' => [ 'id' => 'Qt-GPL-exception-1.0', 'fullname' => 'Qt GPL exception 1.0', 'href' => 'Qt-GPL-exception-1.0.html' ],
		'Qt-LGPL-exception-1.1' => [ 'id' => 'Qt-LGPL-exception-1.1', 'fullname' => 'Qt LGPL exception 1.1', 'href' => 'Qt-LGPL-exception-1.1.html' ],
		'Qwt-exception-1.0' => [ 'id' => 'Qwt-exception-1.0', 'fullname' => 'Qwt exception 1.0', 'href' => 'Qwt-exception-1.0.html' ],
		'SHL-2.0' => [ 'id' => 'SHL-2.0', 'fullname' => 'Solderpad Hardware License v2.0', 'href' => 'SHL-2.0.html' ],
		'SHL-2.1' => [ 'id' => 'SHL-2.1', 'fullname' => 'Solderpad Hardware License v2.1', 'href' => 'SHL-2.1.html' ],
		'SWI-exception' => [ 'id' => 'SWI-exception', 'fullname' => 'SWI exception', 'href' => 'SWI-exception.html' ],
		'Swift-exception' => [ 'id' => 'Swift-exception', 'fullname' => 'Swift Exception', 'href' => 'Swift-exception.html' ],
		'u-boot-exception-2.0' => [ 'id' => 'u-boot-exception-2.0', 'fullname' => 'U-Boot exception 2.0', 'href' => 'u-boot-exception-2.0.html' ],
		'Universal-FOSS-exception-1.0' => [ 'id' => 'Universal-FOSS-exception-1.0', 'fullname' => 'Universal FOSS Exception, Version 1.0', 'href' => 'Universal-FOSS-exception-1.0.html' ],
		'WxWindows-exception-3.1' => [ 'id' => 'WxWindows-exception-3.1', 'fullname' => 'WxWindows Library Exception 3.1', 'href' => 'WxWindows-exception-3.1.html' ],
		'x11vnc-openssl-exception' => [ 'id' => 'x11vnc-openssl-exception', 'fullname' => 'x11vnc OpenSSL Exception', 'href' => 'x11vnc-openssl-exception.html' ],
	);


	static function href(string $license) : string
	{
		if ($license !== '')
		{
			$orig_license = $license;
			foreach (array_reverse(preg_split('/( OR | AND | or | and )/', $orig_license, 0, PREG_SPLIT_OFFSET_CAPTURE)) as $l)
			{
				$k = str_replace('(', '', $l[0]);
				$k = str_replace(')', '', $k);
				$exception = '';
				if (preg_match('/(.*) WITH (.*)/', $k, $match, PREG_OFFSET_CAPTURE))
				{
					$k = $match[1][0];
					$exception = $match[2][0];
					if (array_key_exists($exception, self::$license_exceptions))
					{
						$exception = '<a href="' . self::$spdx_org . self::$license_exceptions[$exception]['href'] . '">' . $exception . '</a>';
					}
					$exception = ' WITH ' . $exception;
				}
				if (array_key_exists($k, self::$licenses))
				{
					$license = substr($license, 0, $l[1]) . '<a href="' . self::$spdx_org . self::$licenses[$k]['href'] . '">' . htmlspecialchars($k) . '</a>' . $exception . substr($license, $l[1] + strlen($l[0]));
				}
			}
		}
		return $license;
	}


	static function check(string $filename, string $license) : bool
	{
		if ($license !== '')
		{
			$orig_license = $license;
			foreach (array_reverse(preg_split('/( OR | AND | or | and )/', $orig_license, 0, PREG_SPLIT_OFFSET_CAPTURE)) as $l)
			{
				$k = str_replace('(', '', $l[0]);
				$k = str_replace(')', '', $k);
				$exception = '';
				if (preg_match('/(.*) WITH (.*)/', $k, $match, PREG_OFFSET_CAPTURE))
				{
					$k = $match[1][0];
					$exception = $match[2][0];
					if (!array_key_exists($exception, self::$license_exceptions))
					{
						fprintf(STDERR, "%s: unknown license exception %s\n", $filename, $exception);
					}
				}
				if (!array_key_exists($k, self::$licenses))
				{
					fprintf(STDERR, "%s: unknown SPDX license identifer %s\n", $filename, $k);
				}
			}
		}
		return true;
	}
}

?>
